// ============================================================================
// FUENTES — Record<string, DataSource> (fuente única en el repo)
// ============================================================================
// Contenido migrado TAL CUAL de las líneas "Fuente:" ya verificadas del sitio
// (CCI Data y los instrumentos de la portada). No se reescriben ni se inventan.
// Los títulos en inglés son nombres propios de la fuente y se conservan.
// ============================================================================

import type { DataSource } from "./tipos-indicadores";

const ACCESSED = "2026-08-22"; // fecha de verificación de esta migración inicial
const ACCESSED_VIT = "2026-08-29"; // verificación de las fuentes de /data/vit

export const FUENTES: Record<string, DataSource> = {
  "mgi-2017": {
    id: "mgi-2017",
    shortLabel: "McKinsey Global Institute (2017)",
    organization: "McKinsey Global Institute",
    title: "Reinventing Construction / Improving construction productivity",
    url: "https://www.mckinsey.com/capabilities/operations/our-insights/improving-construction-productivity",
    publicationDate: "2017",
    accessedAt: ACCESSED,
    documentType: "informe",
    geography: "internacional",
  },
  "dodge-2020": {
    id: "dodge-2020",
    shortLabel: "Dodge Data & Analytics (2020)",
    organization: "Dodge Data & Analytics",
    title: "Prefabrication and Modular Construction 2020 SmartMarket Report",
    url: "https://www.construction.com/resource/prefabrication-modular-construction-2020/",
    publicationDate: "2020",
    accessedAt: ACCESSED,
    documentType: "informe",
    geography: "internacional",
  },
  "asce-2024": {
    id: "asce-2024",
    shortLabel: "ASCE · JME (2024)",
    organization: "Journal of Management in Engineering (ASCE)",
    title: "Construction Waste Reduction in Buildings through Modular and Offsite Construction",
    url: "https://ascelibrary.org/doi/10.1061/JMENEA.MEENG-5828",
    publicationDate: "2024",
    accessedAt: ACCESSED,
    documentType: "estudio",
    geography: "internacional",
  },
  "censo-2024": {
    id: "censo-2024",
    shortLabel: "MINVU · Censo 2024",
    organization: "MINVU · Centro de Estudios (INE)",
    title: "Déficit Habitacional Cuantitativo, Censo 2024",
    url: "https://centrodeestudios.minvu.gob.cl/deficit-habitacional-censo-2024/",
    publicationDate: "2025",
    accessedAt: ACCESSED,
    documentType: "censo",
    geography: "Chile",
  },
  "peh-2025": {
    id: "peh-2025",
    shortLabel: "MINVU · Plan de Emergencia Habitacional",
    organization: "Ministerio de Vivienda y Urbanismo",
    title: "Plan de Emergencia Habitacional, reporte agosto 2025",
    url: "https://www.minvu.gob.cl/plan-de-emergencia-habitacional/",
    publicationDate: "2025",
    accessedAt: ACCESSED,
    documentType: "registro_oficial",
    geography: "Chile",
  },
  "iplc-2025": {
    id: "iplc-2025",
    shortLabel: "Estudio IPLC 2025",
    organization: "Observatorio de Productividad · CChC · CDT (Construye2025)",
    title: "Estudio y análisis del Indicador de Productividad Laboral de la Construcción 2025",
    url: "https://www.cdt.cl/bibliotecatecnica/estudio-y-analisis-del-indicador-de-productividad-laboral-de-la-construccion-2025",
    publicationDate: "2025",
    accessedAt: ACCESSED,
    documentType: "estudio",
    geography: "Chile",
    notes: "Edificación en altura; 74 proyectos 2023-2024; 25 empresas.",
    muestra: { proyectos: 74, empresas: 25 },
  },
  "matrix-2020": {
    id: "matrix-2020",
    shortLabel: "Matrix 2020 (en IPLC 2025)",
    organization: "Matrix Consulting",
    title: "Impulsar la productividad de la industria de la Construcción en Chile a estándares mundiales",
    // Se enlaza a la reproducción pública (Estudio IPLC 2025); el original no está en línea.
    url: "https://www.cdt.cl/bibliotecatecnica/estudio-y-analisis-del-indicador-de-productividad-laboral-de-la-construccion-2025",
    publicationDate: "2020",
    accessedAt: ACCESSED,
    documentType: "estudio",
    geography: "Chile",
    notes: "Reproducido en el Estudio IPLC 2025 (Observatorio de Productividad CChC · CDT).",
  },
  construye2025: {
    id: "construye2025",
    shortLabel: "Construye2025",
    organization: "Construye2025",
    title: "Observatorio de Productividad — resultados IPLC",
    url: "https://construye2025.cl/",
    publicationDate: "2025",
    accessedAt: ACCESSED,
    documentType: "informe",
    geography: "Chile",
  },
  "ditec-minvu": {
    id: "ditec-minvu",
    shortLabel: "MINVU · DITEC",
    organization: "MINVU · División Técnica de Estudio y Fomento Habitacional (DITEC)",
    title: "Construcción Industrializada · Listado de empresas industrializadoras y fichas VIT",
    url: "https://www.minvu.gob.cl/construccion-industrializada/",
    publicationDate: "2026",
    accessedAt: ACCESSED,
    documentType: "registro_oficial",
    geography: "Chile",
  },
  "inn-nch3744": {
    id: "inn-nch3744",
    shortLabel: "INN · NCh3744:2023",
    organization: "Instituto Nacional de Normalización (INN)",
    title: "NCh3744:2023 — Construcción industrializada y prefabricada",
    accessedAt: ACCESSED,
    documentType: "norma",
    geography: "Chile",
    notes:
      "Norma oficial; nació de un anteproyecto impulsado por el CCI, Construye2025 y el MINVU.",
  },
  "guia-cci-2024": {
    id: "guia-cci-2024",
    shortLabel: "Guía CCI 2024",
    organization: "Consejo de Construcción Industrializada (CCI)",
    title: "Guía Práctica de Integración Temprana en Construcción Industrializada",
    url: "/recursos/guia-integracion-temprana-cci-2024.pdf",
    publicationDate: "2024",
    accessedAt: ACCESSED,
    documentType: "guia",
    geography: "Chile",
  },

  // --- Fuentes del Glosario (Fase 3 · ajuste 2), verificadas 2026-08-23 --------
  buildingsmart: {
    id: "buildingsmart",
    shortLabel: "buildingSMART International",
    organization: "buildingSMART International",
    title: "openBIM e Industry Foundation Classes (IFC) — estándares abiertos",
    url: "https://www.buildingsmart.org/",
    accessedAt: "2026-08-23",
    documentType: "otro",
    geography: "internacional",
    notes:
      "Organización que define los estándares abiertos internacionales (openBIM, IFC, IDS, BCF). Dominio oficial; el sitio responde 403 a bots (anti-bot), verificado como oficial.",
  },
  planbim: {
    id: "planbim",
    shortLabel: "Planbim (Corfo)",
    organization: "Planbim · Corfo",
    title: "Estándar BIM para proyectos públicos de Chile",
    url: "https://www.planbim.cl/",
    accessedAt: "2026-08-23",
    documentType: "otro",
    geography: "Chile",
    notes:
      "Programa de Corfo; desarrolló el Estándar BIM para Proyectos Públicos (referencia estable). Construye2025 informa que el programa está actualmente suspendido por financiamiento, por lo que se cita en tiempo neutro: el hecho estable es el Estándar publicado. Dominio oficial confirmado; no accesible por curl desde el entorno de build (000).",
  },
  "minvu-res-52": {
    id: "minvu-res-52",
    shortLabel: "MINVU · Res. Ex. N.º 52 (2023)",
    organization: "Ministerio de Vivienda y Urbanismo (MINVU)",
    title: "Resolución Exenta N.º 52 — Evaluación y aprobación de empresas industrializadoras",
    url: "https://www.minvu.gob.cl/wp-content/uploads/2023/01/Res-Ex-N-52-EVALUACION-Y-APROBACION-DE-EMPRESAS-INDUSTRIALIZADORAS.pdf",
    publicationDate: "2023",
    accessedAt: "2026-08-23",
    documentType: "registro_oficial",
    geography: "Chile",
  },
  "minvu-res-59": {
    id: "minvu-res-59",
    shortLabel: "MINVU · Res. Ex. N.º 59 (2023)",
    organization: "Ministerio de Vivienda y Urbanismo (MINVU)",
    title: "Resolución Exenta N.º 59 — Condiciones de aprobación de Vivienda Industrializada Tipo",
    url: "https://www.minvu.gob.cl/wp-content/uploads/2026/04/Res-Ex-59-17.01.2023-Condiciones-Aprobacion-Vivienda-Industrializada-Tipo.pdf",
    publicationDate: "2023",
    accessedAt: "2026-08-23",
    documentType: "registro_oficial",
    geography: "Chile",
  },

  // --- Fuentes cargadas y verificadas contra el PDF oficial (P0-2), 2026-08-27 ---
  "cnep-2025": {
    id: "cnep-2025",
    shortLabel: "CNEP · Informe Anual de Productividad 2025",
    organization: "Comisión Nacional de Evaluación y Productividad (CNEP)",
    title: "Informe Anual de Productividad 2025",
    url: "https://cnep.cl/cnep/estudios-publicados/informes-anuales-productividad/informe-anual-de-productividad-2025/Informe-Anual-2025-Final.pdf",
    publicationDate: "2025",
    accessedAt: "2026-08-27",
    documentType: "informe",
    geography: "Chile",
    notes:
      "PTF del sector construcción 2024 (-2,0%) y disminución anual promedio 1996-2019 (-3,1%); productividad laboral sectorial relativa al nivel agregado en Figura 1.A.8.",
  },
  "cnp-construccion-2020": {
    id: "cnp-construccion-2020",
    shortLabel: "CNP · Productividad en la Construcción (2020)",
    organization: "Comisión Nacional de Productividad (CNP)",
    title: "Productividad en el Sector de la Construcción — Informe Final",
    url: "https://cnep.cl/cnep/estudios-publicados/sectores-y-areas-transversales/productividad-sector-construccion-2020/Productividad-Sector-Construccion_.pdf",
    publicationDate: "2020",
    accessedAt: "2026-08-27",
    documentType: "informe",
    geography: "Chile",
    notes:
      "Infraestructura vial: muestra de 49 obras de 13 empresas (datos 2019, benchmark Matrix). Productividad como valor agregado por persona-día; desviación de plazo respecto a lo programado.",
    muestra: { proyectos: 49, empresas: 13 },
  },
  "barreras-cfs-2022": {
    id: "barreras-cfs-2022",
    shortLabel: "Barreras CFS Chile (2022)",
    organization: "Construye2025 · CCI · CIPYCS · GEPUC (Pontificia Universidad Católica)",
    title:
      "Identificación y Evaluación de Impacto de Barreras presentes en la adopción de la Construcción Fuera de Sitio en Chile",
    url: "https://construye2025.cl/wp-content/uploads/2022/07/IMPACTO-DE-BARRERAS-PRESENTES-EN-LA-ADOPCION-DE-LA-CONSTRUCCION-FUERA-DE-SITIO-EN-CHILE.pdf",
    publicationDate: "2022",
    accessedAt: "2026-08-27",
    documentType: "estudio",
    geography: "Chile",
    notes:
      "Encuesta a 113 profesionales de la construcción industrializada (más del 90% ingenieros, constructores civiles y arquitectos; 50% tomadores de decisiones; 77% con 16+ años de experiencia). Los porcentajes son el promedio de respuestas de alto/muy alto impacto de cada barrera.",
  },
  "bim-dgop-2025": {
    id: "bim-dgop-2025",
    shortLabel: "MOP · Plan de Implementación BIM DGOP 2025-2028",
    organization: "Ministerio de Obras Públicas · Dirección General de Obras Públicas (DGOP)",
    title: "Estrategia y Plan de Implementación de BIM en DGOP 2025-2028",
    url: "https://repositoriodirplan.mop.gob.cl/biblioteca/bitstreams/e95c3920-d467-41e2-ad1d-b2de69e079c7/download",
    publicationDate: "2025",
    accessedAt: "2026-08-27",
    documentType: "informe",
    geography: "Chile",
    notes:
      "Diagnóstico y plan en un solo documento. Tabla 'Avance de BIM por Dirección' (columnas Central, Regional, Porcentaje por Dirección), resultado de la Medición de Avance de BIM.",
  },
  "mop-obras-2026": {
    id: "mop-obras-2026",
    shortLabel: "MOP · 70 obras estratégicas (abril 2026)",
    organization: "Ministerio de Obras Públicas (MOP)",
    title:
      "MOP define 70 obras estratégicas para acelerar la inversión y la generación de empleo en todo el país",
    url: "https://dcyf.mop.gob.cl/mop-define-70-obras-estrategicas-para-acelerar-la-inversion-y-la-generacion-de-empleo-en-todo-el-pais/",
    publicationDate: "2026-04-21",
    accessedAt: "2026-08-28",
    documentType: "comunicado",
    geography: "Chile",
    notes:
      "Cartera priorizada tras un análisis técnico de más de 300 obras; inversión equivalente al 8,6% del PIB; entre 200 mil y 250 mil empleos directos e indirectos proyectados hacia 2030.",
  },
  "mop-madera-2026": {
    id: "mop-madera-2026",
    shortLabel: "MOP · Madera en la obra pública (2026)",
    organization: "Ministerio de Obras Públicas (MOP)",
    title: "En Chile la madera está presente en la obra pública",
    url: "https://www.mop.gob.cl/en-chile-la-madera-esta-presente-en-la-obra-publica/",
    publicationDate: "2026-04-22",
    accessedAt: "2026-08-27",
    documentType: "otro",
    geography: "Chile",
    notes:
      "Nota institucional (sin cifras cargadas). Menciona industrialización con madera estructural certificada y estandarizada, formación y adopción de BIM, y mecanismos de pago por avance en fábrica.",
  },

  // ==========================================================================
  // VIVIENDA INDUSTRIALIZADA EN LA POLÍTICA PÚBLICA (/data/vit) — fuentes Ditec
  // Minvu + elaboración propia CCI. Añadidas sin tocar las existentes.
  // ==========================================================================
  "minvu-398": {
    id: "minvu-398",
    shortLabel: "Minvu · publicación N°398 (dic 2025)",
    organization: "Ministerio de Vivienda y Urbanismo",
    title:
      "Vivienda industrializada: nuevas tecnologías para diversificar la vivienda de interés público en Chile",
    url: "https://www.minvu.gob.cl/",
    publicationDate: "2025-12-01",
    accessedAt: ACCESSED_VIT,
    documentType: "informe",
    geography: "Chile",
    notes: "Publicación oficial N°398, dic 2025, 116 págs. Corte de sus cifras: nov 2025.",
  },
  "ditec-matta": {
    id: "ditec-matta",
    shortLabel: "Ditec · Marco normativo y aprobación (29 may 2026)",
    organization: "Ditec · Ministerio de Vivienda y Urbanismo",
    title: "Industrialización en vivienda: marco normativo y aprobación",
    url: "https://construccionindustrializada.cl/",
    publicationDate: "2026-05-29",
    accessedAt: ACCESSED_VIT,
    documentType: "comunicado",
    geography: "Chile",
    notes:
      "Presentación institucional del Seminario Vivienda Industrializada, 29 may 2026, publicada por el CCI. requiereCaveat: lámina de seminario, no informe estadístico.",
  },
  "ditec-jara": {
    id: "ditec-jara",
    shortLabel: "Ditec · Res. Ex. N°52 (29 may 2026)",
    organization: "Ditec · Ministerio de Vivienda y Urbanismo",
    title: "Res. Ex. N°52: estándares para la evaluación de empresas industrializadoras",
    url: "https://construccionindustrializada.cl/",
    publicationDate: "2026-05-29",
    accessedAt: ACCESSED_VIT,
    documentType: "comunicado",
    geography: "Chile",
    notes:
      "Presentación institucional del Seminario Vivienda Industrializada, 29 may 2026. requiereCaveat: lámina de seminario, no informe estadístico.",
  },
  "ditec-soto": {
    id: "ditec-soto",
    shortLabel: "Ditec · Industrialización en vivienda (29 may 2026)",
    organization: "Ditec · Ministerio de Vivienda y Urbanismo",
    title: "Industrialización en vivienda",
    url: "https://construccionindustrializada.cl/",
    publicationDate: "2026-05-29",
    accessedAt: ACCESSED_VIT,
    documentType: "comunicado",
    geography: "Chile",
    notes:
      "Presentación institucional del Seminario Vivienda Industrializada, 29 may 2026. requiereCaveat: lámina de seminario, no informe estadístico.",
  },
  "ditec-calderon": {
    id: "ditec-calderon",
    shortLabel: "Ditec · Diagnóstico desde lo avanzado (29 may 2026)",
    organization: "Ditec · Ministerio de Vivienda y Urbanismo",
    title: "Industrialización habitacional: construyendo la capacidad que Chile necesita",
    url: "https://construccionindustrializada.cl/",
    publicationDate: "2026-05-29",
    accessedAt: ACCESSED_VIT,
    documentType: "comunicado",
    geography: "Chile",
    notes:
      "Presentación institucional del Seminario Vivienda Industrializada, 29 may 2026. requiereCaveat: lámina de seminario, no informe estadístico.",
  },
  "res52-levantamiento": {
    id: "res52-levantamiento",
    shortLabel: "Levantamiento industrializadoras Res. Ex. N°52 (29 may 2026)",
    organization: "Industrializadoras certificadas Res. Ex. N°52",
    title: "Oportunidades de mejora para escalar la industrialización",
    url: "https://construccionindustrializada.cl/",
    publicationDate: "2026-05-29",
    accessedAt: ACCESSED_VIT,
    documentType: "otro",
    geography: "Chile",
    notes:
      "Encuesta sectorial entre las industrializadoras certificadas, seminario 29 may 2026. requiereCaveat: dato declarado por las empresas, sin metodología publicada.",
  },
  "circular-023": {
    id: "circular-023",
    shortLabel: "Circular N°023 Subsecretaría VyU (16 may 2025)",
    organization: "Subsecretaría de Vivienda y Urbanismo",
    title: "Circular N°023: implementación del proceso de viviendas industrializadas tipo",
    url: "https://www.minvu.gob.cl/",
    publicationDate: "2025-05-16",
    accessedAt: ACCESSED_VIT,
    documentType: "registro_oficial",
    geography: "Chile",
    notes: "Circular N°023, 16 may 2025, 9 págs. + 4 anexos.",
  },
  "minvu-ci-web": {
    id: "minvu-ci-web",
    shortLabel: "Minvu · Construcción Industrializada (web, 3 jun 2026)",
    organization: "Ministerio de Vivienda y Urbanismo",
    title: "Sección Construcción Industrializada",
    url: "https://www.minvu.gob.cl/",
    publicationDate: "2026-06-03",
    accessedAt: ACCESSED_VIT,
    documentType: "otro",
    geography: "Chile",
    notes: "Sección web del Minvu, actualizada al 3 jun 2026 (fichas VIT y listado de empresas).",
  },
  "cci-fichas-vit": {
    id: "cci-fichas-vit",
    shortLabel: "CCI · Elaboración propia sobre 24 fichas VIT",
    organization: "Consejo de Construcción Industrializada (CCI)",
    title:
      "Elaboración propia sobre las 24 fichas de vivienda industrializada tipo publicadas por la Ditec",
    publicationDate: "2026-06-03",
    accessedAt: ACCESSED_VIT,
    documentType: "otro",
    geography: "Chile",
    notes:
      "Materialidad y superficie transcritas de las 24 fichas oficiales de la Ditec (actualizadas al 3 jun 2026). Alcance: cubre las 24 fichas en línea, no las 47 VIT aprobadas.",
  },
};
