// ============================================================================
// INDICADORES — Record<string, DataIndicator> (fuente única de las CIFRAS)
// ============================================================================
// Todas las cifras del inventario del Paso 1, claveadas por slug. Verificadas en
// la fase 1 (lastVerifiedAt 2026-08-22). Consumidas por la portada y /data vía
// src/lib/datos/indice.ts. NADA se inventa; cada cifra apunta a una fuente.
// ============================================================================

import type { DataIndicator } from "./tipos-indicadores";

// Defaults comunes de la migración inicial.
function mk(
  i: Omit<DataIndicator, "verificationStatus" | "lastVerifiedAt" | "owner" | "version"> &
    Partial<Pick<DataIndicator, "verificationStatus" | "lastVerifiedAt" | "owner" | "version">>
): DataIndicator {
  return {
    verificationStatus: "verified",
    lastVerifiedAt: "2026-08-22",
    owner: "editor CCI",
    version: 1,
    ...i,
  };
}

const IPLC_SCOPE = "Edificación en altura; 74 proyectos 2023-2024 (25 empresas).";
const REVIEW_ESTUDIOS = "2027-08-22";
const REVIEW_DITEC = "2026-11-22";
const REVIEW_VIVIENDA = "2027-03-01";

const LISTA: DataIndicator[] = [
  // ---- Instrumentos de la portada (velocímetros) — también CCI Data cap 01 ----
  mk({
    slug: "potencial-productividad",
    title: "Potencial de productividad",
    shortTitle: "Potencial",
    description:
      "Pasar a una producción industrializada tipo manufactura puede multiplicar la productividad entre 5 y 10 veces, según McKinsey Global Institute.",
    value: 10,
    prefix: "5 a ",
    suffix: "x",
    geography: "internacional",
    cutoffDate: "2017-01-01",
    category: "productividad",
    tags: ["productividad", "potencial", "mckinsey"],
    sourceId: "mgi-2017",
    sourceType: "international",
    scope: "Estimación de McKinsey Global Institute para el paso a producción tipo manufactura.",
    visualizationType: "velocimetro",
    nextReviewAt: REVIEW_ESTUDIOS,
    featured: true,
  }),
  mk({
    slug: "calidad-percepcion",
    title: "Calidad",
    description:
      "9 de cada 10 profesionales que construyen de forma industrializada reportan mejor calidad que con la construcción tradicional, junto a mejor productividad y mayor certeza de plazos.",
    value: 90,
    suffix: "%",
    geography: "internacional",
    cutoffDate: "2020-01-01",
    category: "otro",
    tags: ["calidad", "encuesta"],
    sourceId: "dodge-2020",
    sourceType: "international",
    scope: "Encuesta SmartMarket a profesionales del sector (Dodge Data & Analytics, 2020).",
    visualizationType: "velocimetro",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "residuos-reduccion",
    title: "Menos residuos",
    description:
      "Un estudio de 59 edificios con construcción industrializada off-site midió cerca de un 80% menos de residuos de construcción.",
    value: 80,
    prefix: "−",
    suffix: "%",
    geography: "internacional",
    cutoffDate: "2024-01-01",
    category: "residuos",
    tags: ["residuos"],
    sourceId: "asce-2024",
    sourceType: "international",
    scope: "Estudio de 59 edificios (Journal of Management in Engineering, ASCE, 2024).",
    visualizationType: "velocimetro",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),

  // ---- CCI Data · Cap 01: la oportunidad ----
  mk({
    slug: "deficit-habitacional",
    title: "Déficit habitacional en Chile",
    description:
      "Requerimientos de nuevas viviendas estimados a partir del Censo 2024. Equivale al 7,5% de los hogares del país.",
    value: 491904,
    unit: "viviendas",
    geography: "Chile",
    cutoffDate: "2024-12-31",
    category: "vivienda",
    tags: ["vivienda", "deficit", "censo"],
    sourceId: "censo-2024",
    sourceType: "official_chile",
    scope:
      "Déficit habitacional cuantitativo nacional estimado a partir del Censo 2024 (MINVU · Centro de Estudios · INE).",
    visualizationType: "contador",
    nextReviewAt: REVIEW_VIVIENDA,
    featured: true,
  }),
  mk({
    slug: "meta-habitacional",
    title: "Meta del Plan de Emergencia Habitacional 2022-2026",
    shortTitle: "Meta habitacional",
    description:
      "Viviendas que el Estado se comprometió a entregar en el período de gobierno 2022-2026 para reducir el déficit habitacional.",
    value: 260000,
    unit: "viviendas",
    geography: "Chile",
    period: "2022-2026",
    cutoffDate: "2025-08-31",
    category: "vivienda",
    tags: ["vivienda", "meta", "peh"],
    sourceId: "peh-2025",
    sourceType: "official_chile",
    scope: "Meta del Plan de Emergencia Habitacional del MINVU para el período 2022-2026.",
    visualizationType: "contador",
    nextReviewAt: REVIEW_VIVIENDA,
  }),

  // ---- Cap 02: el desafío (Matrix 2020, reproducido en IPLC 2025) ----
  mk({
    slug: "productividad-chile",
    title: "Productividad laboral — Chile",
    description: "Productividad laboral promedio de la construcción en Chile.",
    value: 0.24,
    unit: "m²/persona-día",
    geography: "Chile",
    cutoffDate: "2020-01-01",
    category: "productividad",
    tags: ["productividad", "chile", "brecha"],
    sourceId: "matrix-2020",
    sourceType: "academic",
    scope:
      "Productividad laboral de la construcción en Chile (Matrix Consulting 2020, reproducido en el Estudio IPLC 2025).",
    visualizationType: "duelo",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "productividad-internacional",
    title: "Productividad laboral — estándar internacional",
    description: "Estándar internacional de referencia de productividad laboral.",
    value: 0.37,
    unit: "m²/persona-día",
    geography: "internacional",
    cutoffDate: "2020-01-01",
    category: "productividad",
    tags: ["productividad", "internacional", "brecha"],
    sourceId: "matrix-2020",
    sourceType: "international",
    scope:
      "Estándar internacional de referencia (Matrix Consulting 2020, reproducido en el Estudio IPLC 2025).",
    visualizationType: "duelo",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "brecha-productividad",
    title: "Brecha de productividad Chile vs. internacional",
    description: "Diferencia entre la productividad laboral de Chile y el estándar internacional.",
    value: 53,
    prefix: "+",
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2020-01-01",
    category: "productividad",
    tags: ["productividad", "brecha"],
    sourceId: "matrix-2020",
    sourceType: "academic",
    scope: "Brecha entre Chile y el estándar internacional (Matrix 2020, en Estudio IPLC 2025).",
    visualizationType: "texto",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),

  // ---- Cap 03: por qué ocurre (IPLC 2025) ----
  mk({
    slug: "iplc-p10",
    title: "P10 — el 10% menos productivo",
    description: "Décimo percentil de productividad laboral entre las obras medidas.",
    value: 0.19,
    unit: "m²/persona-día",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "productividad",
    tags: ["productividad", "iplc", "dispersion"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "iplc-p90",
    title: "P90 — el 10% más productivo",
    description: "Nonagésimo percentil de productividad laboral entre las obras medidas.",
    value: 0.33,
    unit: "m²/persona-día",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "productividad",
    tags: ["productividad", "iplc", "dispersion"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "iplc-brecha-deciles",
    title: "Brecha entre el mejor y el peor decil de obras",
    description: "Diferencia de productividad entre el decil superior e inferior de obras.",
    value: 74,
    prefix: "+",
    suffix: "%",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "productividad",
    tags: ["productividad", "iplc", "dispersion"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "texto",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),

  // ---- Cap 04: la respuesta — industrializar (IPLC 2025) ----
  mk({
    slug: "iplc-productividad-sin-mmc",
    title: "Productividad sin MMC",
    description: "Productividad laboral en obras sin métodos modernos de construcción.",
    value: 0.22,
    unit: "m²/persona-día",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "productividad",
    tags: ["productividad", "iplc", "mmc"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "duelo",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "iplc-productividad-con-mmc",
    title: "Productividad con MMC",
    description: "Productividad laboral en obras con métodos modernos de construcción.",
    value: 0.27,
    unit: "m²/persona-día",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "productividad",
    tags: ["productividad", "iplc", "mmc"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "duelo",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "iplc-residuos-sin-mmc",
    title: "Residuos sin MMC",
    description: "Intensidad de residuos en obras sin métodos modernos de construcción.",
    value: 0.33,
    unit: "m³/m²",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "residuos",
    tags: ["residuos", "iplc", "mmc"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "duelo",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "iplc-residuos-con-mmc",
    title: "Residuos con MMC",
    description: "Intensidad de residuos en obras con métodos modernos de construcción.",
    value: 0.23,
    unit: "m³/m²",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "residuos",
    tags: ["residuos", "iplc", "mmc"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "duelo",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "iplc-atrasos-sin-mmc",
    title: "Obras fuera de plazo sin MMC",
    description: "Porcentaje de obras que terminan fuera de plazo sin métodos modernos de construcción.",
    value: 30,
    suffix: "%",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "plazos",
    tags: ["plazos", "iplc", "mmc"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "duelo",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "iplc-atrasos-con-mmc",
    title: "Obras fuera de plazo con MMC",
    description: "Porcentaje de obras que terminan fuera de plazo con métodos modernos de construcción.",
    value: 10,
    suffix: "%",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "plazos",
    tags: ["plazos", "iplc", "mmc"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "duelo",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "iplc-productividad-bim",
    title: "Productividad con coordinación BIM",
    description: "Mayor productividad laboral asociada a la coordinación BIM.",
    value: 21,
    prefix: "+",
    suffix: "%",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "bim",
    tags: ["bim", "iplc", "productividad"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),

  // ---- Cap 05: Chile ya avanza ----
  mk({
    slug: "productividad-sectorial-crecimiento",
    title: "Productividad sectorial desde 2020",
    description: "0,24 → 0,26 m²/persona-día",
    value: 8,
    prefix: "+",
    suffix: "%",
    geography: "Chile",
    period: "2020-2025",
    cutoffDate: "2024-12-31",
    category: "productividad",
    tags: ["productividad", "iplc"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "productividad-empresas-remedidas",
    title: "Productividad en empresas re-medidas",
    description: "Aumento de productividad en empresas que volvieron a medirse.",
    value: 17,
    prefix: "+",
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2025-01-01",
    category: "productividad",
    tags: ["productividad", "construye2025"],
    sourceId: "construye2025",
    sourceType: "survey",
    scope: "Empresas re-medidas por el Observatorio de Productividad (Construye2025).",
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "industrializadoras-certificadas",
    title: "Empresas industrializadoras certificadas por la DITEC",
    shortTitle: "Industrializadoras DITEC",
    description: "Empresas únicas aprobadas por la DITEC del MINVU (Res. Ex. N°52).",
    value: 24,
    geography: "Chile",
    cutoffDate: "2026-06-03",
    category: "adopcion",
    tags: ["ditec", "adopcion", "minvu"],
    sourceId: "ditec-minvu",
    sourceType: "official_chile",
    scope: "Listado oficial de empresas industrializadoras aprobadas por la DITEC (empresas únicas).",
    visualizationType: "contador",
    nextReviewAt: REVIEW_DITEC,
  }),
  mk({
    slug: "tipologias-vit",
    title: "Tipologías VIT aprobadas por la DITEC",
    shortTitle: "Tipologías VIT",
    description: "Tipologías de Vivienda Industrializada Tipo aprobadas por la DITEC.",
    value: 42,
    geography: "Chile",
    cutoffDate: "2026-06-03",
    category: "adopcion",
    tags: ["ditec", "vit", "minvu"],
    sourceId: "ditec-minvu",
    sourceType: "official_chile",
    scope: "Registro oficial DITEC de tipologías de Vivienda Industrializada Tipo aprobadas.",
    visualizationType: "contador",
    nextReviewAt: REVIEW_DITEC,
  }),
  mk({
    slug: "convenios-ditec",
    title: "Industrializadoras en convenio con DITEC",
    shortTitle: "Convenios DITEC",
    description: "Empresas industrializadoras en convenio con la DITEC del MINVU.",
    value: 6,
    geography: "Chile",
    cutoffDate: "2026-06-03",
    category: "adopcion",
    tags: ["ditec", "convenios", "minvu"],
    sourceId: "ditec-minvu",
    sourceType: "official_chile",
    scope: "Registro oficial DITEC — convenios con industrializadoras.",
    visualizationType: "contador",
    lastVerifiedAt: "2026-08-23",
    nextReviewAt: REVIEW_DITEC,
  }),
  mk({
    slug: "nch3744",
    title: "Norma oficial de construcción industrializada",
    description:
      "La norma NCh3744:2023, oficializada por el Instituto Nacional de Normalización (INN), nació de un anteproyecto impulsado por el CCI, Construye2025 y el MINVU. Fija el lenguaje común del sector.",
    value: "NCh3744:2023",
    geography: "Chile",
    cutoffDate: "2023-01-01",
    category: "normativa",
    tags: ["normativa", "inn", "nch3744"],
    sourceId: "inn-nch3744",
    sourceType: "official_chile",
    scope: "Norma chilena oficial de construcción industrializada y prefabricada (terminología).",
    visualizationType: "texto",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "residuos-sectorial-2020",
    title: "Residuos sectoriales 2020",
    description: "Intensidad de residuos sectorial en 2020.",
    value: 0.27,
    unit: "m³/m²",
    geography: "Chile",
    period: "2020",
    cutoffDate: "2024-12-31",
    category: "residuos",
    tags: ["residuos", "iplc", "sectorial"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "texto",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "residuos-sectorial-2025",
    title: "Residuos sectoriales 2025",
    description: "Intensidad de residuos sectorial en 2025.",
    value: 0.25,
    unit: "m³/m²",
    geography: "Chile",
    period: "2025",
    cutoffDate: "2024-12-31",
    category: "residuos",
    tags: ["residuos", "iplc", "sectorial"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "texto",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),

  // ---- Cap 06: la evidencia — casos documentados (Guía CCI 2024) ----
  mk({
    slug: "caso-baumax-productividad",
    title: "Baumax — productividad (m²/hd)",
    description: "Aumento de productividad en cinco edificios con paneles de hormigón.",
    value: 35,
    prefix: "+",
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2024-01-01",
    category: "casos",
    tags: ["caso", "baumax", "productividad"],
    sourceId: "guia-cci-2024",
    sourceType: "documented_case",
    scope: "Caso Baumax documentado en la Guía Práctica de Integración Temprana, CCI (2024).",
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "caso-baumax-residuos",
    title: "Baumax — residuos",
    description: "Reducción de residuos en cinco edificios con paneles de hormigón.",
    value: 60,
    prefix: "−",
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2024-01-01",
    category: "casos",
    tags: ["caso", "baumax", "residuos"],
    sourceId: "guia-cci-2024",
    sourceType: "documented_case",
    scope: "Caso Baumax documentado en la Guía Práctica de Integración Temprana, CCI (2024).",
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "caso-baumax-retrabajos",
    title: "Baumax — retrabajos",
    description: "Reducción de retrabajos en cinco edificios con paneles de hormigón.",
    value: 80,
    prefix: "−",
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2024-01-01",
    category: "casos",
    tags: ["caso", "baumax", "retrabajos"],
    sourceId: "guia-cci-2024",
    sourceType: "documented_case",
    scope: "Caso Baumax documentado en la Guía Práctica de Integración Temprana, CCI (2024).",
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "caso-socovesa-coordinacion",
    title: "Socovesa Olimpia II — tiempo de coordinación",
    description: "Reducción del tiempo de coordinación con BIM en Olimpia II.",
    value: 60,
    prefix: "−",
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2024-01-01",
    category: "casos",
    tags: ["caso", "socovesa", "bim"],
    sourceId: "guia-cci-2024",
    sourceType: "documented_case",
    scope: "Caso Socovesa Sur · BIM Lab · Spoerer (Olimpia II), Guía CCI (2024).",
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "caso-socovesa-adicionales",
    title: "Socovesa Olimpia II — adicionales de obra",
    description: "Adicionales de obra como porcentaje del contrato.",
    value: 0.14,
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2024-01-01",
    category: "casos",
    tags: ["caso", "socovesa", "costos"],
    sourceId: "guia-cci-2024",
    sourceType: "documented_case",
    scope: "Caso Socovesa Sur · BIM Lab · Spoerer (Olimpia II), Guía CCI (2024).",
    caveat: "vs 2-3% histórico",
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "caso-boetsch-ahorro",
    title: "Boetsch · Spoerer — ahorro de costo directo",
    description: "Ahorro del costo directo por optimización estructural temprana.",
    value: 0.92,
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2024-01-01",
    category: "casos",
    tags: ["caso", "boetsch", "costos"],
    sourceId: "guia-cci-2024",
    sourceType: "documented_case",
    scope: "Caso Boetsch · Spoerer Ingenieros (optimización estructural temprana), Guía CCI (2024).",
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "socovesa-rdi",
    title: "Socovesa Olimpia II — RDI",
    description: "Reducción de RDI (consultas o solicitudes de información en obra) por coordinación temprana con BIM.",
    value: 43,
    prefix: "−",
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2024-01-01",
    category: "casos",
    tags: ["caso", "socovesa", "bim"],
    sourceId: "guia-cci-2024",
    sourceType: "documented_case",
    scope: "caso Olimpia II; Guía CCI 2024, p. 62",
    visualizationType: "contador",
    lastVerifiedAt: "2026-08-24",
    nextReviewAt: "2027-08-22",
  }),
  mk({
    slug: "boetsch-iteraciones-bim",
    title: "Boetsch · Spoerer — iteraciones en BIM",
    description: "Reducción de iteraciones y modificaciones en BIM por integración temprana en el diseño.",
    value: 30,
    prefix: "−",
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2024-01-01",
    category: "casos",
    tags: ["caso", "boetsch", "bim"],
    sourceId: "guia-cci-2024",
    sourceType: "documented_case",
    scope: "caso Boetsch/Spoerer; Guía CCI 2024, p. 69",
    visualizationType: "contador",
    lastVerifiedAt: "2026-08-24",
    nextReviewAt: "2027-08-22",
  }),
];

export const INDICADORES: Record<string, DataIndicator> = Object.fromEntries(
  LISTA.map((i) => [i.slug, i])
);

// Lista original (conserva orden de declaración) para validaciones/recorridos.
export const INDICADORES_LISTA = LISTA;
