// ============================================================================
// INDICADORES — "Vivienda industrializada en la política pública" (/data/vit)
// ============================================================================
// Registro tipado de las cifras de la sección VIT. Fuente: publicaciones y
// presentaciones de la Ditec Minvu + elaboración propia del CCI sobre las 24
// fichas. Se concatena a INDICADORES_LISTA en indicadores.ts. NADA se inventa;
// cada cifra apunta a una fuente y trae fecha de corte. Los tipos declarados
// (sector_survey) llevan caveat obligatorio, validado en build.
// ============================================================================

import type { DataIndicator } from "./tipos-indicadores";

const VERIF = "2026-08-29";
const REVISAR = "2026-11-30"; // cadencia Ditec

function mkv(
  i: Omit<DataIndicator, "verificationStatus" | "lastVerifiedAt" | "owner" | "version" | "geography"> &
    Partial<Pick<DataIndicator, "geography" | "verificationStatus" | "lastVerifiedAt" | "owner" | "version">>
): DataIndicator {
  return {
    geography: "Chile",
    verificationStatus: "verified",
    lastVerifiedAt: VERIF,
    owner: "editor CCI",
    version: 1,
    nextReviewAt: REVISAR,
    ...i,
  };
}

const CAVEAT_DECLARADO =
  "Dato declarado por las empresas en el levantamiento de las industrializadoras Res. Ex. N°52, sin metodología publicada.";
const CAVEAT_MACROZONA =
  "Distribución por macrozona en verificación con la Ditec: suma 61 sobre 47 VIT y las 24 fichas publicadas declaran alcance nacional, así que no describe disponibilidad regional.";

export const INDICADORES_VIT: DataIndicator[] = [
  // ---------------------------------------------------------------- REGISTRO
  mkv({ slug: "autorizaciones-res52", title: "Autorizaciones vigentes Res. Ex. N°52", description: "Autorizaciones vigentes de empresas industrializadoras (Res. Ex. N°52).", value: 25, unit: "autorizaciones", cutoffDate: "2026-02-11", category: "vivienda", tags: ["vit", "registro", "res52"], sourceId: "ditec-jara", sourceType: "official_chile", scope: "Autorizaciones vigentes de industrializadoras (Res. Ex. N°52), corte 11 feb 2026." }),
  mkv({ slug: "autorizaciones-res52-2025", title: "Autorizaciones Res. Ex. N°52 (nov 2025)", description: "Autorizaciones de industrializadoras al corte de nov 2025.", value: 22, unit: "autorizaciones", cutoffDate: "2025-11-01", category: "vivienda", tags: ["vit", "registro", "res52", "serie"], sourceId: "minvu-398", sourceType: "official_chile", scope: "Autorizaciones vigentes de industrializadoras (Res. Ex. N°52), corte nov 2025." }),
  mkv({ slug: "empresas-res52", title: "Empresas industrializadoras autorizadas", description: "Empresas distintas con autorización vigente Res. Ex. N°52.", value: 23, unit: "empresas", cutoffDate: "2026-02-11", category: "vivienda", tags: ["vit", "registro", "res52"], sourceId: "ditec-jara", sourceType: "official_chile", scope: "Empresas distintas autorizadas (Res. Ex. N°52), corte feb 2026.", caveat: "25 autorizaciones vigentes corresponden a 23 empresas: Tecnotruss y Eterna tienen dos cada una." }),
  mkv({ slug: "empresas-con-vit", title: "Industrializadoras con al menos una VIT", description: "Empresas autorizadas que además tienen al menos una VIT aprobada.", value: 9, unit: "empresas", cutoffDate: "2026-05-01", category: "vivienda", tags: ["vit", "registro"], sourceId: "ditec-calderon", sourceType: "official_chile", scope: "Industrializadoras con al menos una VIT aprobada, corte may 2026." }),
  mkv({ slug: "autorizaciones-norte", title: "Autorizaciones en la macrozona norte", description: "Autorizaciones Res. Ex. N°52 en la zona norte.", value: 1, unit: "autorizaciones", cutoffDate: "2026-02-11", category: "vivienda", tags: ["vit", "registro", "macrozona"], sourceId: "ditec-jara", sourceType: "official_chile", scope: "Autorizaciones vigentes en la macrozona norte, feb 2026." }),
  mkv({ slug: "autorizaciones-centro", title: "Autorizaciones en la macrozona centro", description: "Autorizaciones Res. Ex. N°52 en la zona centro.", value: 17, unit: "autorizaciones", cutoffDate: "2026-02-11", category: "vivienda", tags: ["vit", "registro", "macrozona"], sourceId: "ditec-jara", sourceType: "official_chile", scope: "Autorizaciones vigentes en la macrozona centro, feb 2026." }),
  mkv({ slug: "autorizaciones-sur", title: "Autorizaciones en la macrozona sur", description: "Autorizaciones Res. Ex. N°52 en la zona sur.", value: 7, unit: "autorizaciones", cutoffDate: "2026-02-11", category: "vivienda", tags: ["vit", "registro", "macrozona"], sourceId: "ditec-jara", sourceType: "official_chile", scope: "Autorizaciones vigentes en la macrozona sur, feb 2026." }),

  // --------------------------------------------------------------------- VIT
  mkv({ slug: "vit-aprobadas", title: "VIT aprobadas", description: "Viviendas industrializadas tipo aprobadas por la Ditec.", value: 47, unit: "VIT", cutoffDate: "2026-05-01", category: "vivienda", tags: ["vit", "aprobadas"], sourceId: "ditec-calderon", sourceType: "official_chile", scope: "VIT aprobadas por la Ditec, corte may 2026 (en manos de 9 industrializadoras)." }),
  mkv({ slug: "vit-aprobadas-2025", title: "VIT aprobadas (nov 2025)", description: "VIT aprobadas al corte de nov 2025.", value: 43, unit: "VIT", cutoffDate: "2025-11-01", category: "vivienda", tags: ["vit", "aprobadas", "serie"], sourceId: "minvu-398", sourceType: "official_chile", scope: "VIT aprobadas por la Ditec, corte nov 2025." }),
  mkv({ slug: "vit-ingresadas", title: "Proyectos VIT ingresados", description: "Proyectos VIT presentados a la Ditec.", value: 102, unit: "proyectos", cutoffDate: "2025-11-01", category: "vivienda", tags: ["vit", "embudo"], sourceId: "minvu-398", sourceType: "official_chile", scope: "Proyectos VIT ingresados a evaluación en la Ditec, corte nov 2025." }),
  mkv({ slug: "vit-devueltas", title: "Proyectos VIT devueltos", description: "Proyectos VIT devueltos por no cumplir mínimos técnicos.", value: 19, unit: "proyectos", cutoffDate: "2025-11-01", category: "vivienda", tags: ["vit", "embudo"], sourceId: "minvu-398", sourceType: "official_chile", scope: "Proyectos VIT devueltos, corte nov 2025." }),
  mkv({ slug: "vit-en-revision", title: "Proyectos VIT en revisión", description: "Proyectos VIT en proceso iterativo de revisión.", value: 40, unit: "proyectos", cutoffDate: "2025-11-01", category: "vivienda", tags: ["vit", "embudo"], sourceId: "minvu-398", sourceType: "official_chile", scope: "Proyectos VIT en revisión en la Ditec, corte nov 2025." }),
  mkv({ slug: "vit-ds49", title: "VIT aprobadas para DS49", description: "VIT aprobadas para el programa DS49.", value: 34, unit: "VIT", cutoffDate: "2025-11-01", category: "vivienda", tags: ["vit", "ds49"], sourceId: "minvu-398", sourceType: "official_chile", scope: "VIT aprobadas para DS49, corte nov 2025 (sobre 43).", caveat: "Suman 44 con las 10 DS10 porque una vivienda está aprobada para ambos programas." }),
  mkv({ slug: "vit-ds10", title: "VIT aprobadas para DS10", description: "VIT aprobadas para el programa DS10.", value: 10, unit: "VIT", cutoffDate: "2025-11-01", category: "vivienda", tags: ["vit", "ds10"], sourceId: "minvu-398", sourceType: "official_chile", scope: "VIT aprobadas para DS10, corte nov 2025 (sobre 43)." }),
  mkv({ slug: "vit-edificios-3pisos", title: "VIT de edificios de más de 3 pisos", description: "VIT que corresponden a edificios de más de 3 pisos.", value: 5, unit: "VIT", cutoffDate: "2026-05-01", category: "vivienda", tags: ["vit", "altura"], sourceId: "res52-levantamiento", sourceType: "sector_survey", scope: "VIT de edificios de más de 3 pisos, levantamiento Res. Ex. N°52, may 2026.", caveat: CAVEAT_DECLARADO }),
  mkv({ slug: "dias-revision-ditec", title: "Días de revisión en la Ditec", description: "Días promedio de revisión de una VIT en la Ditec.", value: 168, unit: "días", cutoffDate: "2025-11-01", category: "plazos", tags: ["vit", "plazos", "ditec"], sourceId: "minvu-398", sourceType: "official_chile", scope: "Días promedio de revisión de una VIT, medidos por la Ditec, corte nov 2025." }),
  mkv({ slug: "vit-macrozona-abcde", title: "VIT emplazables en zonas A–E", description: "VIT que pueden emplazarse en zonas térmicas A–E (norte y centro).", value: 39, unit: "VIT", cutoffDate: "2026-05-01", category: "vivienda", tags: ["vit", "termica", "macrozona"], sourceId: "ditec-calderon", sourceType: "official_chile", scope: "VIT emplazables en zonas térmicas A–E, may 2026.", caveat: CAVEAT_MACROZONA }),
  mkv({ slug: "vit-macrozona-fg", title: "VIT emplazables en zonas F–G", description: "VIT que pueden emplazarse en zonas térmicas F–G (sur).", value: 19, unit: "VIT", cutoffDate: "2026-05-01", category: "vivienda", tags: ["vit", "termica", "macrozona"], sourceId: "ditec-calderon", sourceType: "official_chile", scope: "VIT emplazables en zonas térmicas F–G, may 2026.", caveat: CAVEAT_MACROZONA }),
  mkv({ slug: "vit-macrozona-hi", title: "VIT emplazables en zonas H–I", description: "VIT que pueden emplazarse en zonas térmicas H–I (extremo austral).", value: 3, unit: "VIT", cutoffDate: "2026-05-01", category: "vivienda", tags: ["vit", "termica", "macrozona"], sourceId: "ditec-calderon", sourceType: "official_chile", scope: "VIT emplazables en zonas térmicas H–I, may 2026.", caveat: CAVEAT_MACROZONA }),

  // -------------------------------------------------------------- PRODUCCIÓN
  mkv({ slug: "unidades-industrializadas", title: "Viviendas industrializadas", description: "Unidades habitacionales industrializadas en DS10, DS19 y DS49.", value: 14613, unit: "viviendas", cutoffDate: "2026-05-01", category: "vivienda", tags: ["produccion"], sourceId: "ditec-calderon", sourceType: "official_chile", scope: "Viviendas industrializadas en 365 proyectos (DS10, DS19, DS49), corte may 2026." }),
  mkv({ slug: "proyectos-industrializados", title: "Proyectos industrializados", description: "Proyectos habitacionales con vivienda industrializada.", value: 365, unit: "proyectos", cutoffDate: "2026-05-01", category: "vivienda", tags: ["produccion"], sourceId: "ditec-calderon", sourceType: "official_chile", scope: "Proyectos con vivienda industrializada, corte may 2026." }),
  mkv({ slug: "unidades-ejecutadas", title: "Viviendas industrializadas ejecutadas", description: "Unidades industrializadas ya ejecutadas (acumulado).", value: 2933, unit: "viviendas", cutoffDate: "2026-05-01", category: "vivienda", tags: ["produccion", "estado"], sourceId: "ditec-calderon", sourceType: "official_chile", scope: "Viviendas industrializadas ejecutadas, acumulado en DS10/DS19/DS49, corte may 2026." }),
  mkv({ slug: "unidades-en-ejecucion", title: "Viviendas en ejecución", description: "Unidades industrializadas en ejecución.", value: 3605, unit: "viviendas", cutoffDate: "2026-05-01", category: "vivienda", tags: ["produccion", "estado"], sourceId: "ditec-calderon", sourceType: "official_chile", scope: "Viviendas industrializadas en ejecución, corte may 2026." }),
  mkv({ slug: "unidades-en-desarrollo", title: "Viviendas en desarrollo", description: "Unidades industrializadas en desarrollo.", value: 6548, unit: "viviendas", cutoffDate: "2026-05-01", category: "vivienda", tags: ["produccion", "estado"], sourceId: "ditec-calderon", sourceType: "official_chile", scope: "Viviendas industrializadas en desarrollo, corte may 2026." }),
  mkv({ slug: "unidades-por-iniciar", title: "Viviendas próximas a iniciar", description: "Unidades industrializadas próximas a iniciar.", value: 1292, unit: "viviendas", cutoffDate: "2026-05-01", category: "vivienda", tags: ["produccion", "estado"], sourceId: "ditec-calderon", sourceType: "official_chile", scope: "Viviendas industrializadas próximas a iniciar, corte may 2026." }),
  mkv({ slug: "unidades-sin-inicio", title: "Viviendas seleccionadas sin inicio", description: "Unidades industrializadas seleccionadas sin inicio.", value: 235, unit: "viviendas", cutoffDate: "2026-05-01", category: "vivienda", tags: ["produccion", "estado"], sourceId: "ditec-calderon", sourceType: "official_chile", scope: "Viviendas industrializadas seleccionadas sin inicio, corte may 2026." }),

  // ---------------------------------------------------------------- CAPACIDAD
  mkv({ slug: "capacidad-efectiva-mes", title: "Capacidad efectiva mensual", description: "Capacidad efectiva de producción informada a la Ditec, al mes.", value: 1652, unit: "viviendas/mes", cutoffDate: "2026-05-01", category: "vivienda", tags: ["capacidad"], sourceId: "minvu-398", sourceType: "official_chile", scope: "Capacidad efectiva informada por la red autorizada (Minvu N°398 + Ditec «Industrialización en vivienda», 29 may 2026)." }),
  mkv({ slug: "capacidad-efectiva-anio", title: "Capacidad efectiva anual", description: "Capacidad efectiva de producción informada a la Ditec, al año.", value: 19824, unit: "viviendas/año", cutoffDate: "2026-05-01", category: "vivienda", tags: ["capacidad"], sourceId: "minvu-398", sourceType: "official_chile", scope: "Capacidad efectiva anual informada por la red autorizada (Minvu N°398 + Ditec, 29 may 2026)." }),
  mkv({ slug: "capacidad-potencial-mes", title: "Capacidad potencial mensual", description: "Capacidad potencial informada por la red autorizada, al mes.", value: 2020, unit: "viviendas/mes", cutoffDate: "2026-05-01", category: "vivienda", tags: ["capacidad"], sourceId: "ditec-soto", sourceType: "official_chile", scope: "Capacidad potencial mensual informada por la red autorizada (Ditec «Industrialización en vivienda», 29 may 2026, y Minvu N°398)." }),
  mkv({ slug: "capacidad-potencial-anio", title: "Capacidad potencial anual", description: "Capacidad potencial informada por la red autorizada, al año.", value: 24240, unit: "viviendas/año", cutoffDate: "2026-05-01", category: "vivienda", tags: ["capacidad"], sourceId: "ditec-soto", sourceType: "official_chile", scope: "Capacidad potencial anual informada (4.416 más que la efectiva), Ditec 29 may 2026 y Minvu N°398." }),
  mkv({ slug: "autorizaciones-sin-vit", title: "Autorizaciones sin VIT aprobada", description: "Autorizaciones vigentes que aún no tienen ninguna VIT aprobada.", value: 16, unit: "autorizaciones", cutoffDate: "2026-02-11", category: "vivienda", tags: ["capacidad", "registro"], sourceId: "ditec-jara", sourceType: "official_chile", scope: "Autorizaciones vigentes sin VIT aprobada, feb 2026.", caveat: "Derivado: 25 autorizaciones vigentes menos las 9 industrializadoras con al menos una VIT." }),
  mkv({ slug: "dias-equivalentes-ejecutado", title: "Días equivalentes de lo ejecutado", description: "Días que la red instalada tardaría en producir todo lo ejecutado hasta hoy.", value: 54, unit: "días", cutoffDate: "2026-05-01", category: "plazos", tags: ["capacidad", "derivado"], sourceId: "ditec-calderon", sourceType: "official_chile", scope: "Cociente entre las 2.933 viviendas ejecutadas y la capacidad anual de 19.824, expresado en días.", caveat: "Derivado: 2.933 ÷ 19.824 × 365. Compara un acumulado con un flujo anual, y se publica con esa advertencia." }),

  // ----------------------------------------------------- DESEMPEÑO DEL SISTEMA
  mkv({ slug: "programacion-industrial", title: "Programación con lógica industrial", description: "Viviendas en ejecución cuya programación de plazos aprovecha la eficiencia industrial.", value: 17, suffix: "%", cutoffDate: "2025-11-01", category: "plazos", tags: ["desempeno"], sourceId: "minvu-398", sourceType: "official_chile", scope: "Viviendas en ejecución con programación de plazos de lógica industrial, corte nov 2025." }),
  mkv({ slug: "avance-normal", title: "Proyectos con avance normal", description: "Proyectos que avanzan con normalidad.", value: 81, suffix: "%", cutoffDate: "2025-11-01", category: "plazos", tags: ["desempeno"], sourceId: "minvu-398", sourceType: "official_chile", scope: "Proyectos con avance normal, corte nov 2025." }),
  mkv({ slug: "demora-organismos-externos", title: "Demoras por organismos externos", description: "Demoras en proyectos en desarrollo explicadas por gestión con organismos externos.", value: 44, suffix: "%", cutoffDate: "2025-11-01", category: "plazos", tags: ["desempeno"], sourceId: "minvu-398", sourceType: "official_chile", scope: "Demoras explicadas por gestión con organismos externos, corte nov 2025." }),
  mkv({ slug: "demora-gestion-interna", title: "Demoras por gestión interna", description: "Demoras por tiempos de gestión interna: evaluación, concursos, licitaciones.", value: 15, suffix: "%", cutoffDate: "2025-11-01", category: "plazos", tags: ["desempeno"], sourceId: "minvu-398", sourceType: "official_chile", scope: "Demoras por gestión interna (evaluación, concursos, licitaciones), corte nov 2025." }),

  // -------------------------------------------------------- PLAZOS 52 m² (total)
  mkv({ slug: "llave-en-mano-fabrica-volumetrica", title: "Plazo llave en mano — volumétrico en fábrica", description: "Días para una vivienda de 52 m² con sistema volumétrico en fábrica, llave en mano.", value: 14, unit: "días", cutoffDate: "2026-05-01", category: "plazos", tags: ["plazos", "52m2"], sourceId: "ditec-calderon", sourceType: "official_chile", scope: "Caso de referencia de 52 m², volumétrico en fábrica, desde permiso a recepción (Ditec, 29 may 2026)." }),
  mkv({ slug: "llave-en-mano-panelizada", title: "Plazo llave en mano — panelizada en fábrica", description: "Días para una vivienda de 52 m² panelizada en fábrica, llave en mano.", value: 39, unit: "días", cutoffDate: "2026-05-01", category: "plazos", tags: ["plazos", "52m2"], sourceId: "ditec-calderon", sourceType: "official_chile", scope: "Caso de referencia de 52 m², panelizada en fábrica, desde permiso a recepción (Ditec, 29 may 2026)." }),
  mkv({ slug: "llave-en-mano-tradicional", title: "Plazo llave en mano — tradicional in situ", description: "Días para una vivienda de 52 m² construida de forma tradicional in situ.", value: 172, unit: "días", cutoffDate: "2026-05-01", category: "plazos", tags: ["plazos", "52m2"], sourceId: "ditec-calderon", sourceType: "official_chile", scope: "Caso de referencia de 52 m², tradicional in situ, desde permiso a recepción (Ditec, 29 may 2026)." }),

  // ------------------------------------------- DECLARADO POR LA INDUSTRIA (caveat)
  mkv({ slug: "uso-capacidad-declarado", title: "Uso declarado de la capacidad instalada", description: "Uso estimado de la capacidad instalada declarado por las industrializadoras.", value: 13, suffix: "%", cutoffDate: "2026-05-01", category: "vivienda", tags: ["capacidad", "declarado"], sourceId: "res52-levantamiento", sourceType: "sector_survey", scope: "Uso estimado de la capacidad instalada declarado en el levantamiento Res. Ex. N°52, may 2026.", caveat: CAVEAT_DECLARADO }),
  mkv({ slug: "escenario-uso-actual", title: "Escenario de uso actual (13%)", description: "Viviendas al año con el uso actual declarado de la capacidad instalada.", value: 2577, unit: "viviendas/año", cutoffDate: "2026-05-01", category: "vivienda", tags: ["capacidad", "declarado", "escenario"], sourceId: "res52-levantamiento", sourceType: "sector_survey", scope: "Escenario de producción anual con uso del 13% de la capacidad instalada.", caveat: CAVEAT_DECLARADO }),
  mkv({ slug: "escenario-uso-50", title: "Escenario de uso 50%", description: "Viviendas al año si el uso de la capacidad instalada fuera 50%.", value: 9912, unit: "viviendas/año", cutoffDate: "2026-05-01", category: "vivienda", tags: ["capacidad", "declarado", "escenario"], sourceId: "res52-levantamiento", sourceType: "sector_survey", scope: "Escenario de producción anual con uso del 50% de la capacidad instalada.", caveat: CAVEAT_DECLARADO }),
  mkv({ slug: "escenario-uso-80", title: "Escenario de uso 80%", description: "Viviendas al año si el uso de la capacidad instalada fuera 80%.", value: 15859, unit: "viviendas/año", cutoffDate: "2026-05-01", category: "vivienda", tags: ["capacidad", "declarado", "escenario"], sourceId: "res52-levantamiento", sourceType: "sector_survey", scope: "Escenario de producción anual con uso del 80% de la capacidad instalada.", caveat: CAVEAT_DECLARADO }),

  // --------------------------------------- MATERIALIDAD (elaboración propia CCI)
  mkv({ slug: "fichas-publicadas", title: "Fichas VIT publicadas", description: "Fichas de vivienda industrializada tipo en línea en el sitio del Minvu.", value: 24, unit: "fichas", cutoffDate: "2026-06-03", category: "vivienda", tags: ["vit", "materialidad", "fichas"], sourceId: "minvu-ci-web", sourceType: "official_chile", scope: "24 fichas VIT en línea (sección Construcción Industrializada del Minvu) de las 47 aprobadas. Alcance: cubre las 24 fichas en línea, no las 47 VIT aprobadas." }),
  mkv({ slug: "materialidad-madera", title: "Fichas VIT de madera", description: "Fichas cuya materialidad es madera.", value: 10, unit: "fichas", cutoffDate: "2026-06-03", category: "vivienda", tags: ["materialidad", "madera"], sourceId: "cci-fichas-vit", sourceType: "cci_data", scope: "Fichas de materialidad madera, sobre 24 (elaboración propia CCI). Alcance: 24 fichas en línea." }),
  mkv({ slug: "materialidad-panel-sip", title: "Fichas VIT de panel SIP", description: "Fichas cuya materialidad es panel SIP.", value: 6, unit: "fichas", cutoffDate: "2026-06-03", category: "vivienda", tags: ["materialidad", "sip"], sourceId: "cci-fichas-vit", sourceType: "cci_data", scope: "Fichas de materialidad panel SIP, sobre 24 (elaboración propia CCI). Alcance: 24 fichas en línea." }),
  mkv({ slug: "materialidad-acero", title: "Fichas VIT de acero", description: "Fichas cuya materialidad es acero.", value: 4, unit: "fichas", cutoffDate: "2026-06-03", category: "vivienda", tags: ["materialidad", "acero"], sourceId: "cci-fichas-vit", sourceType: "cci_data", scope: "Fichas de materialidad acero, sobre 24 (elaboración propia CCI). Alcance: 24 fichas en línea." }),
  mkv({ slug: "materialidad-hormigon", title: "Fichas VIT de hormigón", description: "Fichas cuya materialidad es hormigón.", value: 3, unit: "fichas", cutoffDate: "2026-06-03", category: "vivienda", tags: ["materialidad", "hormigon"], sourceId: "cci-fichas-vit", sourceType: "cci_data", scope: "Fichas de materialidad hormigón, sobre 24 (elaboración propia CCI). Alcance: 24 fichas en línea." }),
  mkv({ slug: "materialidad-mixto", title: "Fichas VIT mixtas", description: "Fichas cuya materialidad es mixta.", value: 1, unit: "fichas", cutoffDate: "2026-06-03", category: "vivienda", tags: ["materialidad", "mixto"], sourceId: "cci-fichas-vit", sourceType: "cci_data", scope: "Fichas de materialidad mixta, sobre 24 (elaboración propia CCI). Alcance: 24 fichas en línea.", caveat: "Tres clasificaciones están en confirmación (una ficha declara materialidades distintas y otras dos exigen lectura manual)." }),
  mkv({ slug: "superficie-base-min", title: "Superficie base mínima", description: "Superficie base mínima entre las 24 fichas.", value: 50, unit: "m²", cutoffDate: "2026-06-03", category: "vivienda", tags: ["materialidad", "superficie"], sourceId: "cci-fichas-vit", sourceType: "cci_data", scope: "Superficie base mínima entre las 24 fichas publicadas (elaboración propia CCI)." }),
  mkv({ slug: "superficie-base-max", title: "Superficie base máxima", description: "Superficie base máxima entre las 24 fichas.", value: 64, unit: "m²", cutoffDate: "2026-06-03", category: "vivienda", tags: ["materialidad", "superficie"], sourceId: "cci-fichas-vit", sourceType: "cci_data", scope: "Superficie base máxima entre las 24 fichas publicadas (elaboración propia CCI)." }),
  mkv({ slug: "superficie-ampliada-max", title: "Superficie ampliada máxima", description: "Superficie ampliada máxima entre las 24 fichas.", value: 73.6, unit: "m²", cutoffDate: "2026-06-03", category: "vivienda", tags: ["materialidad", "superficie"], sourceId: "cci-fichas-vit", sourceType: "cci_data", scope: "Superficie ampliada máxima entre las 24 fichas publicadas (elaboración propia CCI)." }),

  // ------------------------------------------------- INCENTIVOS (marco normativo)
  mkv({ slug: "anticipo-industrializadora", title: "Anticipo a la industrializadora", description: "Anticipo sobre el monto total de partidas industrializadas, pagado directamente a la industrializadora.", value: 50, suffix: "%", cutoffDate: "2025-05-16", category: "normativa", tags: ["normativa", "incentivo", "pago"], sourceId: "circular-023", sourceType: "official_chile", scope: "Anticipo de hasta 50% de las partidas de fabricación, pagable con calificación definitiva (Circular N°023, gestión de pago), en DS49 y DS10." }),
  mkv({ slug: "programas-vivienda-industrializada", title: "Programas que incorporan vivienda industrializada", description: "Programas habitacionales que incorporan el concepto de vivienda industrializada en sus llamados.", value: 3, unit: "programas", cutoffDate: "2026-05-29", category: "normativa", tags: ["normativa", "programas"], sourceId: "ditec-matta", sourceType: "official_chile", scope: "Programas que incorporan vivienda industrializada: DS10, DS49 y, recientemente, DS19 (Ditec, 29 may 2026).", caveat: "Lámina de seminario, no informe estadístico." }),
];
