// ============================================================================
// INDICADORES — Record<string, DataIndicator> (fuente única de las CIFRAS)
// ============================================================================
// Todas las cifras del inventario del Paso 1, claveadas por slug. Verificadas en
// la fase 1 (lastVerifiedAt 2026-08-22). Consumidas por la portada y /data vía
// src/lib/datos/indice.ts. NADA se inventa; cada cifra apunta a una fuente.
// ============================================================================

import type { DataIndicator } from "./tipos-indicadores";

// Defaults comunes de la migración inicial.
function mk(
  i: Omit<DataIndicator, "verificationStatus" | "lastVerifiedAt" | "owner" | "version"> &
    Partial<Pick<DataIndicator, "verificationStatus" | "lastVerifiedAt" | "owner" | "version">>
): DataIndicator {
  return {
    verificationStatus: "verified",
    lastVerifiedAt: "2026-08-22",
    owner: "editor CCI",
    version: 1,
    ...i,
  };
}

const IPLC_SCOPE = "Edificación en altura; 74 proyectos 2023-2024 (25 empresas).";
const REVIEW_ESTUDIOS = "2027-08-22";
const REVIEW_DITEC = "2026-11-22";
const REVIEW_VIVIENDA = "2027-03-01";

const LISTA: DataIndicator[] = [
  // ---- Instrumentos de la portada (velocímetros) — también CCI Data cap 01 ----
  mk({
    slug: "potencial-productividad",
    title: "Potencial de productividad",
    shortTitle: "Potencial",
    description:
      "Pasar a una producción industrializada tipo manufactura puede multiplicar la productividad entre 5 y 10 veces, según McKinsey Global Institute.",
    value: 10,
    prefix: "5 a ",
    suffix: "x",
    geography: "internacional",
    cutoffDate: "2017-01-01",
    category: "productividad",
    tags: ["productividad", "potencial", "mckinsey"],
    sourceId: "mgi-2017",
    sourceType: "international",
    scope: "Estimación de McKinsey Global Institute para el paso a producción tipo manufactura.",
    visualizationType: "velocimetro",
    nextReviewAt: REVIEW_ESTUDIOS,
    featured: true,
  }),
  mk({
    slug: "calidad-percepcion",
    title: "Calidad",
    description:
      "9 de cada 10 profesionales que construyen de forma industrializada reportan mejor calidad que con la construcción tradicional, junto a mejor productividad y mayor certeza de plazos.",
    value: 90,
    suffix: "%",
    geography: "internacional",
    cutoffDate: "2020-01-01",
    category: "otro",
    tags: ["calidad", "encuesta"],
    sourceId: "dodge-2020",
    sourceType: "international",
    scope: "Encuesta SmartMarket a profesionales del sector (Dodge Data & Analytics, 2020).",
    visualizationType: "velocimetro",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "residuos-reduccion",
    title: "Menos residuos",
    description:
      "Un estudio de 59 edificios con construcción industrializada off-site midió cerca de un 80% menos de residuos de construcción.",
    value: 80,
    prefix: "−",
    suffix: "%",
    geography: "internacional",
    cutoffDate: "2024-01-01",
    category: "residuos",
    tags: ["residuos"],
    sourceId: "asce-2024",
    sourceType: "international",
    scope: "Estudio de 59 edificios (Journal of Management in Engineering, ASCE, 2024).",
    visualizationType: "velocimetro",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),

  // ---- CCI Data · Cap 01: la oportunidad ----
  mk({
    slug: "deficit-habitacional",
    title: "Déficit habitacional en Chile",
    description:
      "Requerimientos de nuevas viviendas estimados a partir del Censo 2024. Equivale al 7,5% de los hogares del país.",
    value: 491904,
    unit: "viviendas",
    geography: "Chile",
    cutoffDate: "2024-12-31",
    category: "vivienda",
    tags: ["vivienda", "deficit", "censo"],
    sourceId: "censo-2024",
    sourceType: "official_chile",
    scope:
      "Déficit habitacional cuantitativo nacional estimado a partir del Censo 2024 (MINVU · Centro de Estudios · INE).",
    visualizationType: "contador",
    nextReviewAt: REVIEW_VIVIENDA,
    featured: true,
  }),
  mk({
    slug: "meta-habitacional",
    title: "Meta del Plan de Emergencia Habitacional 2022-2026",
    shortTitle: "Meta habitacional",
    description:
      "Viviendas que el Estado se comprometió a entregar en el período de gobierno 2022-2026 para reducir el déficit habitacional.",
    value: 260000,
    unit: "viviendas",
    geography: "Chile",
    period: "2022-2026",
    cutoffDate: "2025-08-31",
    category: "vivienda",
    tags: ["vivienda", "meta", "peh"],
    sourceId: "peh-2025",
    sourceType: "official_chile",
    scope: "Meta del Plan de Emergencia Habitacional del MINVU para el período 2022-2026.",
    visualizationType: "contador",
    nextReviewAt: REVIEW_VIVIENDA,
  }),

  // ---- Cap 02: el desafío (Matrix 2020, reproducido en IPLC 2025) ----
  mk({
    slug: "productividad-chile",
    title: "Productividad laboral — Chile",
    description: "Productividad laboral promedio de la construcción en Chile.",
    value: 0.24,
    unit: "m²/persona-día",
    geography: "Chile",
    cutoffDate: "2020-01-01",
    category: "productividad",
    tags: ["productividad", "chile", "brecha"],
    sourceId: "matrix-2020",
    sourceType: "academic",
    scope:
      "Productividad laboral de la construcción en Chile (Matrix Consulting 2020, reproducido en el Estudio IPLC 2025).",
    visualizationType: "duelo",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "productividad-internacional",
    title: "Productividad laboral — estándar internacional",
    description: "Estándar internacional de referencia de productividad laboral.",
    value: 0.37,
    unit: "m²/persona-día",
    geography: "internacional",
    cutoffDate: "2020-01-01",
    category: "productividad",
    tags: ["productividad", "internacional", "brecha"],
    sourceId: "matrix-2020",
    sourceType: "international",
    scope:
      "Estándar internacional de referencia (Matrix Consulting 2020, reproducido en el Estudio IPLC 2025).",
    visualizationType: "duelo",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "brecha-productividad",
    title: "Brecha de productividad Chile vs. internacional",
    description: "Diferencia entre la productividad laboral de Chile y el estándar internacional.",
    value: 53,
    prefix: "+",
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2020-01-01",
    category: "productividad",
    tags: ["productividad", "brecha"],
    sourceId: "matrix-2020",
    sourceType: "academic",
    scope: "Brecha entre Chile y el estándar internacional (Matrix 2020, en Estudio IPLC 2025).",
    visualizationType: "texto",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),

  // ---- Cap 03: por qué ocurre (IPLC 2025) ----
  mk({
    slug: "iplc-p10",
    title: "P10 — el 10% menos productivo",
    description: "Décimo percentil de productividad laboral entre las obras medidas.",
    value: 0.19,
    unit: "m²/persona-día",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "productividad",
    tags: ["productividad", "iplc", "dispersion"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "iplc-p90",
    title: "P90 — el 10% más productivo",
    description: "Nonagésimo percentil de productividad laboral entre las obras medidas.",
    value: 0.33,
    unit: "m²/persona-día",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "productividad",
    tags: ["productividad", "iplc", "dispersion"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "iplc-brecha-deciles",
    title: "Brecha entre el mejor y el peor decil de obras",
    description: "Diferencia de productividad entre el decil superior e inferior de obras.",
    value: 74,
    prefix: "+",
    suffix: "%",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "productividad",
    tags: ["productividad", "iplc", "dispersion"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "texto",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),

  // ---- Cap 04: la respuesta — industrializar (IPLC 2025) ----
  mk({
    slug: "iplc-productividad-sin-mmc",
    title: "Productividad sin MMC",
    description: "Productividad laboral en obras sin métodos modernos de construcción.",
    value: 0.22,
    unit: "m²/persona-día",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "productividad",
    tags: ["productividad", "iplc", "mmc"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "duelo",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "iplc-productividad-con-mmc",
    title: "Productividad con MMC",
    description: "Productividad laboral en obras con métodos modernos de construcción.",
    value: 0.27,
    unit: "m²/persona-día",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "productividad",
    tags: ["productividad", "iplc", "mmc"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "duelo",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "iplc-residuos-sin-mmc",
    title: "Residuos sin MMC",
    description: "Intensidad de residuos en obras sin métodos modernos de construcción.",
    value: 0.33,
    unit: "m³/m²",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "residuos",
    tags: ["residuos", "iplc", "mmc"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "duelo",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "iplc-residuos-con-mmc",
    title: "Residuos con MMC",
    description: "Intensidad de residuos en obras con métodos modernos de construcción.",
    value: 0.23,
    unit: "m³/m²",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "residuos",
    tags: ["residuos", "iplc", "mmc"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "duelo",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "iplc-atrasos-sin-mmc",
    title: "Obras fuera de plazo sin MMC",
    description: "Porcentaje de obras que terminan fuera de plazo sin métodos modernos de construcción.",
    value: 30,
    suffix: "%",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "plazos",
    tags: ["plazos", "iplc", "mmc"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "duelo",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "iplc-atrasos-con-mmc",
    title: "Obras fuera de plazo con MMC",
    description: "Porcentaje de obras que terminan fuera de plazo con métodos modernos de construcción.",
    value: 10,
    suffix: "%",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "plazos",
    tags: ["plazos", "iplc", "mmc"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "duelo",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "iplc-productividad-bim",
    title: "Productividad con coordinación BIM",
    description: "Mayor productividad laboral asociada a la coordinación BIM.",
    value: 21,
    prefix: "+",
    suffix: "%",
    geography: "Chile",
    period: "2023-2024",
    cutoffDate: "2024-12-31",
    category: "bim",
    tags: ["bim", "iplc", "productividad"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),

  // ---- Cap 05: Chile ya avanza ----
  mk({
    slug: "productividad-sectorial-crecimiento",
    title: "Productividad sectorial desde 2020",
    description: "0,24 → 0,26 m²/persona-día",
    value: 8,
    prefix: "+",
    suffix: "%",
    geography: "Chile",
    period: "2020-2025",
    cutoffDate: "2024-12-31",
    category: "productividad",
    tags: ["productividad", "iplc"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "productividad-empresas-remedidas",
    title: "Productividad en empresas re-medidas",
    description: "Aumento de productividad en empresas que volvieron a medirse.",
    value: 17,
    prefix: "+",
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2025-01-01",
    category: "productividad",
    tags: ["productividad", "construye2025"],
    sourceId: "construye2025",
    sourceType: "survey",
    scope: "Empresas re-medidas por el Observatorio de Productividad (Construye2025).",
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "industrializadoras-certificadas",
    title: "Empresas industrializadoras certificadas por la DITEC",
    shortTitle: "Industrializadoras DITEC",
    description: "Empresas únicas aprobadas por la DITEC del MINVU (Res. Ex. N°52).",
    value: 24,
    geography: "Chile",
    cutoffDate: "2026-06-03",
    category: "adopcion",
    tags: ["ditec", "adopcion", "minvu"],
    sourceId: "ditec-minvu",
    sourceType: "official_chile",
    scope: "Listado oficial de empresas industrializadoras aprobadas por la DITEC (empresas únicas).",
    visualizationType: "contador",
    nextReviewAt: REVIEW_DITEC,
  }),
  mk({
    slug: "tipologias-vit",
    title: "Tipologías VIT aprobadas por la DITEC",
    shortTitle: "Tipologías VIT",
    description: "Tipologías de Vivienda Industrializada Tipo aprobadas por la DITEC.",
    value: 42,
    geography: "Chile",
    cutoffDate: "2026-06-03",
    category: "adopcion",
    tags: ["ditec", "vit", "minvu"],
    sourceId: "ditec-minvu",
    sourceType: "official_chile",
    scope: "Registro oficial DITEC de tipologías de Vivienda Industrializada Tipo aprobadas.",
    visualizationType: "contador",
    nextReviewAt: REVIEW_DITEC,
  }),
  mk({
    slug: "convenios-ditec",
    title: "Industrializadoras en convenio con DITEC",
    shortTitle: "Convenios DITEC",
    description: "Empresas industrializadoras en convenio con la DITEC del MINVU.",
    value: 6,
    geography: "Chile",
    cutoffDate: "2026-06-03",
    category: "adopcion",
    tags: ["ditec", "convenios", "minvu"],
    sourceId: "ditec-minvu",
    sourceType: "official_chile",
    scope: "Registro oficial DITEC — convenios con industrializadoras.",
    visualizationType: "contador",
    lastVerifiedAt: "2026-08-23",
    nextReviewAt: REVIEW_DITEC,
  }),
  mk({
    slug: "nch3744",
    title: "Norma oficial de construcción industrializada",
    description:
      "La norma NCh3744:2023, oficializada por el Instituto Nacional de Normalización (INN), nació de un anteproyecto impulsado por el CCI, Construye2025 y el MINVU. Fija el lenguaje común del sector.",
    value: "NCh3744:2023",
    geography: "Chile",
    cutoffDate: "2023-01-01",
    category: "normativa",
    tags: ["normativa", "inn", "nch3744"],
    sourceId: "inn-nch3744",
    sourceType: "official_chile",
    scope: "Norma chilena oficial de construcción industrializada y prefabricada (terminología).",
    visualizationType: "texto",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "residuos-sectorial-2020",
    title: "Residuos sectoriales 2020",
    description: "Intensidad de residuos sectorial en 2020.",
    value: 0.27,
    unit: "m³/m²",
    geography: "Chile",
    period: "2020",
    cutoffDate: "2024-12-31",
    category: "residuos",
    tags: ["residuos", "iplc", "sectorial"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "texto",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "residuos-sectorial-2025",
    title: "Residuos sectoriales 2025",
    description: "Intensidad de residuos sectorial en 2025.",
    value: 0.25,
    unit: "m³/m²",
    geography: "Chile",
    period: "2025",
    cutoffDate: "2024-12-31",
    category: "residuos",
    tags: ["residuos", "iplc", "sectorial"],
    sourceId: "iplc-2025",
    sourceType: "survey",
    scope: IPLC_SCOPE,
    visualizationType: "texto",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),

  // ---- Cap 06: la evidencia — casos documentados (Guía CCI 2024) ----
  mk({
    slug: "caso-baumax-productividad",
    title: "Baumax — productividad (m²/hd)",
    description: "Aumento de productividad en cinco edificios con paneles de hormigón.",
    value: 35,
    prefix: "+",
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2024-01-01",
    category: "casos",
    tags: ["caso", "baumax", "productividad"],
    sourceId: "guia-cci-2024",
    sourceType: "documented_case",
    scope: "Caso Baumax documentado en la Guía Práctica de Integración Temprana, CCI (2024).",
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "caso-baumax-residuos",
    title: "Baumax — residuos",
    description: "Reducción de residuos en cinco edificios con paneles de hormigón.",
    value: 60,
    prefix: "−",
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2024-01-01",
    category: "casos",
    tags: ["caso", "baumax", "residuos"],
    sourceId: "guia-cci-2024",
    sourceType: "documented_case",
    scope: "Caso Baumax documentado en la Guía Práctica de Integración Temprana, CCI (2024).",
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "caso-baumax-retrabajos",
    title: "Baumax — retrabajos",
    description: "Reducción de retrabajos en cinco edificios con paneles de hormigón.",
    value: 80,
    prefix: "−",
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2024-01-01",
    category: "casos",
    tags: ["caso", "baumax", "retrabajos"],
    sourceId: "guia-cci-2024",
    sourceType: "documented_case",
    scope: "Caso Baumax documentado en la Guía Práctica de Integración Temprana, CCI (2024).",
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "caso-socovesa-coordinacion",
    title: "Socovesa Olimpia II — tiempo de coordinación",
    description: "Reducción del tiempo de coordinación con BIM en Olimpia II.",
    value: 60,
    prefix: "−",
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2024-01-01",
    category: "casos",
    tags: ["caso", "socovesa", "bim"],
    sourceId: "guia-cci-2024",
    sourceType: "documented_case",
    scope: "Caso Socovesa Sur · BIM Lab · Spoerer (Olimpia II), Guía CCI (2024).",
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "caso-socovesa-adicionales",
    title: "Socovesa Olimpia II — adicionales de obra",
    description: "Adicionales de obra como porcentaje del contrato.",
    value: 0.14,
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2024-01-01",
    category: "casos",
    tags: ["caso", "socovesa", "costos"],
    sourceId: "guia-cci-2024",
    sourceType: "documented_case",
    scope: "Caso Socovesa Sur · BIM Lab · Spoerer (Olimpia II), Guía CCI (2024).",
    caveat: "vs 2-3% histórico",
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "caso-boetsch-ahorro",
    title: "Boetsch · Spoerer — ahorro de costo directo",
    description: "Ahorro del costo directo por optimización estructural temprana.",
    value: 0.92,
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2024-01-01",
    category: "casos",
    tags: ["caso", "boetsch", "costos"],
    sourceId: "guia-cci-2024",
    sourceType: "documented_case",
    scope: "Caso Boetsch · Spoerer Ingenieros (optimización estructural temprana), Guía CCI (2024).",
    visualizationType: "contador",
    nextReviewAt: REVIEW_ESTUDIOS,
  }),
  mk({
    slug: "socovesa-rdi",
    title: "Socovesa Olimpia II — RDI",
    description: "Reducción de RDI (consultas o solicitudes de información en obra) por coordinación temprana con BIM.",
    value: 43,
    prefix: "−",
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2024-01-01",
    category: "casos",
    tags: ["caso", "socovesa", "bim"],
    sourceId: "guia-cci-2024",
    sourceType: "documented_case",
    scope: "caso Olimpia II; Guía CCI 2024, p. 62",
    visualizationType: "contador",
    lastVerifiedAt: "2026-08-24",
    nextReviewAt: "2027-08-22",
  }),
  mk({
    slug: "boetsch-iteraciones-bim",
    title: "Boetsch · Spoerer — iteraciones en BIM",
    description: "Reducción de iteraciones y modificaciones en BIM por integración temprana en el diseño.",
    value: 30,
    prefix: "−",
    suffix: "%",
    geography: "Chile",
    cutoffDate: "2024-01-01",
    category: "casos",
    tags: ["caso", "boetsch", "bim"],
    sourceId: "guia-cci-2024",
    sourceType: "documented_case",
    scope: "caso Boetsch/Spoerer; Guía CCI 2024, p. 69",
    visualizationType: "contador",
    lastVerifiedAt: "2026-08-24",
    nextReviewAt: "2027-08-22",
  }),

  // ==========================================================================
  // P0-2 · Cargas verificadas contra el PDF oficial (2026-08-27). NO se publican
  // aún en ninguna vista; quedan disponibles para el rediseño de capítulos.
  // ==========================================================================

  // ---- F1 · CNEP — Informe Anual de Productividad 2025 ----
  mk({
    slug: "ptf-construccion-2024",
    title: "PTF del sector construcción, 2024",
    description: "Variación de la Productividad Total de Factores (PTF) del sector construcción en 2024.",
    value: 2.0,
    prefix: "−",
    suffix: "%",
    geography: "Chile",
    period: "2024",
    cutoffDate: "2024-12-31",
    category: "productividad",
    tags: ["productividad", "ptf", "cnep", "construccion"],
    sourceId: "cnep-2025",
    sourceType: "official_chile",
    scope: "PTF del sector construcción en Chile, año 2024 (CNEP, Informe Anual de Productividad 2025).",
    caveat: "Es la variación de la Productividad Total de Factores del sector; no es productividad laboral ni física por trabajador.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "ptf-construccion-1996-2019",
    title: "PTF del sector construcción, promedio anual 1996-2019",
    description: "Disminución anual promedio de la PTF del sector construcción durante 1996-2019.",
    value: 3.1,
    prefix: "−",
    suffix: "%",
    geography: "Chile",
    period: "1996-2019",
    cutoffDate: "2019-12-31",
    category: "productividad",
    tags: ["productividad", "ptf", "cnep", "construccion"],
    sourceId: "cnep-2025",
    sourceType: "official_chile",
    scope: "Disminución anual promedio de la PTF del sector construcción en Chile, período 1996-2019 (CNEP 2025).",
    caveat: "Es la variación de la Productividad Total de Factores del sector; no es productividad laboral ni física por trabajador.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "productividad-relativa-construccion-1990",
    title: "Productividad laboral relativa de la construcción, 1990",
    description: "Productividad laboral del sector construcción relativa al nivel agregado de la economía en 1990.",
    value: 1.7,
    suffix: "x",
    geography: "Chile",
    period: "1990",
    cutoffDate: "1990-12-31",
    category: "productividad",
    tags: ["productividad", "cnep", "construccion", "relativa"],
    sourceId: "cnep-2025",
    sourceType: "official_chile",
    scope: "Productividad laboral del sector construcción relativa al nivel agregado de la economía, año 1990 (CNEP 2025, Figura 1.A.8).",
    caveat: "Es productividad laboral sectorial RELATIVA al promedio de la economía (valor 1 = promedio nacional); no es PTF ni productividad física por trabajador.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "productividad-relativa-construccion-2024",
    title: "Productividad laboral relativa de la construcción, 2024",
    description: "Productividad laboral del sector construcción relativa al nivel agregado de la economía en 2024.",
    value: 0.8,
    suffix: "x",
    geography: "Chile",
    period: "2024",
    cutoffDate: "2024-12-31",
    category: "productividad",
    tags: ["productividad", "cnep", "construccion", "relativa"],
    sourceId: "cnep-2025",
    sourceType: "official_chile",
    scope: "Productividad laboral del sector construcción relativa al nivel agregado de la economía, año 2024 (CNEP 2025, Figura 1.A.8).",
    caveat: "Es productividad laboral sectorial RELATIVA al promedio de la economía (valor 1 = promedio nacional); no es PTF ni productividad física por trabajador.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),

  // ---- F2 · CNP — Productividad en el Sector de la Construcción (2020), infraestructura vial ----
  mk({
    slug: "productividad-vial-chile",
    title: "Productividad en infraestructura vial — Chile",
    description: "Valor agregado por persona-día en obras de infraestructura vial en Chile.",
    value: 99,
    prefix: "US$",
    unit: "USD/persona-día",
    geography: "Chile",
    period: "2019",
    cutoffDate: "2019-12-31",
    category: "productividad",
    tags: ["productividad", "vial", "cnp", "brecha"],
    sourceId: "cnp-construccion-2020",
    sourceType: "official_chile",
    scope: "Productividad (valor agregado por persona-día) en infraestructura vial en Chile; muestra de 49 obras de 13 empresas, datos 2019 (CNP 2020, benchmark Matrix).",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "productividad-vial-internacional",
    title: "Productividad en infraestructura vial — estándar internacional",
    description: "Valor agregado por persona-día en obras de infraestructura vial de la muestra de referentes internacionales.",
    value: 317,
    prefix: "US$",
    unit: "USD/persona-día",
    geography: "internacional",
    period: "2019",
    cutoffDate: "2019-12-31",
    category: "productividad",
    tags: ["productividad", "vial", "cnp", "brecha"],
    sourceId: "cnp-construccion-2020",
    sourceType: "international",
    scope: "Estándar internacional de referencia de productividad en infraestructura vial (CNP 2020, benchmark Matrix; EE.UU., Japón, Suecia, Alemania, Canadá, Reino Unido).",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "desviacion-plazo-vial-chile",
    title: "Desviación de plazo en infraestructura vial — Chile",
    description: "Retraso promedio respecto al plazo programado en obras de infraestructura vial en Chile.",
    value: 27,
    suffix: "%",
    geography: "Chile",
    period: "2019",
    cutoffDate: "2019-12-31",
    category: "plazos",
    tags: ["plazos", "vial", "cnp"],
    sourceId: "cnp-construccion-2020",
    sourceType: "official_chile",
    scope: "Desviación promedio del plazo respecto a lo programado en infraestructura vial en Chile; muestra de 49 obras (CNP 2020).",
    caveat: "Es la magnitud promedio del retraso respecto al plazo programado en la muestra vial; no es el porcentaje de obras que se atrasan.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "desviacion-plazo-vial-internacional",
    title: "Desviación de plazo en infraestructura vial — internacional",
    description: "Retraso promedio respecto al plazo programado en obras de infraestructura vial, referencia internacional.",
    value: 8,
    suffix: "%",
    geography: "internacional",
    period: "2019",
    cutoffDate: "2019-12-31",
    category: "plazos",
    tags: ["plazos", "vial", "cnp"],
    sourceId: "cnp-construccion-2020",
    sourceType: "international",
    scope: "Desviación promedio del plazo respecto a lo programado en infraestructura vial, referencia internacional (CNP 2020).",
    caveat: "Es la magnitud promedio del retraso respecto al plazo programado; no es el porcentaje de obras que se atrasan.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),

  // ---- F3 · Barreras CFS Chile (2022) — encuesta a 113 profesionales ----
  // sourceType "sector_survey": percepción declarada, no medición de obras.
  mk({
    slug: "barrera-cfs-colaboracion",
    title: "Barrera CFS — falta de trabajo colaborativo",
    description: "Profesionales que identifican la falta de trabajo colaborativo entre actores como barrera de alto impacto para adoptar la construcción fuera de sitio.",
    value: 82,
    suffix: "%",
    geography: "Chile",
    period: "2021",
    cutoffDate: "2021-12-31",
    category: "adopcion",
    tags: ["cfs", "barreras", "colaboracion"],
    sourceId: "barreras-cfs-2022",
    sourceType: "sector_survey",
    scope: "Encuesta a 113 profesionales de la construcción industrializada en Chile (Barreras CFS, 2022).",
    caveat: "Porcentaje de profesionales encuestados que identifica la barrera con alto/muy alto impacto; percepción declarada, no medición de obras.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "barrera-cfs-estandarizacion-diseno",
    title: "Barrera CFS — falta de estandarización en el diseño",
    description: "Profesionales que identifican la falta de estandarización en el diseño como barrera de alto impacto para adoptar la construcción fuera de sitio.",
    value: 78,
    suffix: "%",
    geography: "Chile",
    period: "2021",
    cutoffDate: "2021-12-31",
    category: "adopcion",
    tags: ["cfs", "barreras", "estandarizacion"],
    sourceId: "barreras-cfs-2022",
    sourceType: "sector_survey",
    scope: "Encuesta a 113 profesionales de la construcción industrializada en Chile (Barreras CFS, 2022).",
    caveat: "Porcentaje de profesionales encuestados que identifica la barrera con alto/muy alto impacto; percepción declarada, no medición de obras.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "barrera-cfs-integracion-temprana",
    title: "Barrera CFS — falta de integración temprana",
    description: "Profesionales que identifican la falta de integración temprana de la cadena de valor como barrera de alto impacto para adoptar la construcción fuera de sitio.",
    value: 77,
    suffix: "%",
    geography: "Chile",
    period: "2021",
    cutoffDate: "2021-12-31",
    category: "adopcion",
    tags: ["cfs", "barreras", "integracion-temprana"],
    sourceId: "barreras-cfs-2022",
    sourceType: "sector_survey",
    scope: "Encuesta a 113 profesionales de la construcción industrializada en Chile (Barreras CFS, 2022).",
    caveat: "Porcentaje de profesionales encuestados que identifica la barrera con alto/muy alto impacto; percepción declarada, no medición de obras.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "barrera-cfs-definicion-temprana-diseno",
    title: "Barrera CFS — incapacidad de definición temprana del diseño",
    description: "Profesionales que identifican la incapacidad de definición temprana del diseño como barrera de alto impacto para adoptar la construcción fuera de sitio.",
    value: 73,
    suffix: "%",
    geography: "Chile",
    period: "2021",
    cutoffDate: "2021-12-31",
    category: "adopcion",
    tags: ["cfs", "barreras", "diseno"],
    sourceId: "barreras-cfs-2022",
    sourceType: "sector_survey",
    scope: "Encuesta a 113 profesionales de la construcción industrializada en Chile (Barreras CFS, 2022).",
    caveat: "Porcentaje de profesionales encuestados que identifica la barrera con alto/muy alto impacto; percepción declarada, no medición de obras.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "barrera-cfs-estandarizacion-materiales",
    title: "Barrera CFS — poca estandarización de materiales",
    description: "Profesionales que identifican la poca estandarización de materiales y elementos de construcción como barrera de alto impacto para adoptar la construcción fuera de sitio.",
    value: 70,
    suffix: "%",
    geography: "Chile",
    period: "2021",
    cutoffDate: "2021-12-31",
    category: "adopcion",
    tags: ["cfs", "barreras", "estandarizacion", "materiales"],
    sourceId: "barreras-cfs-2022",
    sourceType: "sector_survey",
    scope: "Encuesta a 113 profesionales de la construcción industrializada en Chile (Barreras CFS, 2022).",
    caveat: "Porcentaje de profesionales encuestados que identifica la barrera con alto/muy alto impacto; percepción declarada, no medición de obras.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "barrera-cfs-adopcion-bim",
    title: "Barrera CFS — escasa adopción de BIM",
    description: "Profesionales que identifican la escasa adopción de BIM como barrera de alto impacto para adoptar la construcción fuera de sitio.",
    value: 64,
    suffix: "%",
    geography: "Chile",
    period: "2021",
    cutoffDate: "2021-12-31",
    category: "adopcion",
    tags: ["cfs", "barreras", "bim"],
    sourceId: "barreras-cfs-2022",
    sourceType: "sector_survey",
    scope: "Encuesta a 113 profesionales de la construcción industrializada en Chile (Barreras CFS, 2022).",
    caveat: "Porcentaje de profesionales encuestados que identifica la barrera con alto/muy alto impacto; percepción declarada, no medición de obras.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "barrera-cfs-promocion-insuficiente",
    title: "Barrera CFS — promoción insuficiente",
    description: "Profesionales que identifican la falta de una adecuada promoción de la CFS como barrera de alto impacto para su adopción.",
    value: 83,
    suffix: "%",
    geography: "Chile",
    period: "2021",
    cutoffDate: "2021-12-31",
    category: "adopcion",
    tags: ["cfs", "barreras", "difusion"],
    sourceId: "barreras-cfs-2022",
    sourceType: "sector_survey",
    scope: "Encuesta a 113 profesionales de la construcción industrializada en Chile (Barreras CFS, 2022).",
    caveat: "Porcentaje de profesionales encuestados que identifica la barrera con alto/muy alto impacto; percepción declarada, no medición de obras.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "barrera-cfs-beneficios-no-documentados",
    title: "Barrera CFS — beneficios económicos no documentados",
    description: "Profesionales que identifican la inadecuada documentación de los beneficios económicos de la CFS como barrera de alto impacto para su adopción.",
    value: 78,
    suffix: "%",
    geography: "Chile",
    period: "2021",
    cutoffDate: "2021-12-31",
    category: "adopcion",
    tags: ["cfs", "barreras", "difusion", "beneficios"],
    sourceId: "barreras-cfs-2022",
    sourceType: "sector_survey",
    scope: "Encuesta a 113 profesionales de la construcción industrializada en Chile (Barreras CFS, 2022).",
    caveat: "Porcentaje de profesionales encuestados que identifica la barrera con alto/muy alto impacto; percepción declarada, no medición de obras.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "barrera-cfs-numero-proveedores",
    title: "Barrera CFS — limitado número de proveedores",
    description: "Profesionales que identifican el limitado número de proveedores de fabricación fuera de sitio como barrera de alto impacto para adoptar la CFS.",
    value: 74,
    suffix: "%",
    geography: "Chile",
    period: "2021",
    cutoffDate: "2021-12-31",
    category: "adopcion",
    tags: ["cfs", "barreras", "proveedores", "mercado"],
    sourceId: "barreras-cfs-2022",
    sourceType: "sector_survey",
    scope: "Encuesta a 113 profesionales de la construcción industrializada en Chile (Barreras CFS, 2022).",
    caveat: "Porcentaje de profesionales encuestados que identifica la barrera con alto/muy alto impacto; percepción declarada, no medición de obras.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "barrera-cfs-costos-indirectos",
    title: "Barrera CFS — falta de reconocimiento de costos indirectos",
    description: "Profesionales que identifican la falta de reconocimiento de los costos indirectos en obras como barrera de alto impacto para adoptar la CFS.",
    value: 72,
    suffix: "%",
    geography: "Chile",
    period: "2021",
    cutoffDate: "2021-12-31",
    category: "adopcion",
    tags: ["cfs", "barreras", "costos", "financiero"],
    sourceId: "barreras-cfs-2022",
    sourceType: "sector_survey",
    scope: "Encuesta a 113 profesionales de la construcción industrializada en Chile (Barreras CFS, 2022).",
    caveat: "Porcentaje de profesionales encuestados que identifica la barrera con alto/muy alto impacto; percepción declarada, no medición de obras.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "barrera-cfs-evaluar-beneficios",
    title: "Barrera CFS — dificultad para evaluar objetivamente los beneficios",
    description: "Profesionales que identifican la incapacidad para evaluar objetivamente los beneficios de la CFS como barrera de alto impacto para su adopción.",
    value: 76,
    suffix: "%",
    geography: "Chile",
    period: "2021",
    cutoffDate: "2021-12-31",
    category: "adopcion",
    tags: ["cfs", "barreras", "habilidades", "beneficios"],
    sourceId: "barreras-cfs-2022",
    sourceType: "sector_survey",
    scope: "Encuesta a 113 profesionales de la construcción industrializada en Chile (Barreras CFS, 2022).",
    caveat: "Porcentaje de profesionales encuestados que identifica la barrera con alto/muy alto impacto; percepción declarada, no medición de obras.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),

  // ---- F4 · MOP·DGOP — Plan de Implementación BIM DGOP 2025-2028 ----
  // Tabla "Avance de BIM por Dirección" (columna "Porcentaje por Dirección").
  mk({
    slug: "bim-dgop-total",
    title: "Avance de BIM en la DGOP — total",
    description: "Avance total de implementación de BIM en las Direcciones de la DGOP (Porcentaje por Dirección, fila Total).",
    value: 17.7,
    suffix: "%",
    geography: "Chile",
    period: "2025",
    cutoffDate: "2025-01-01",
    category: "bim",
    tags: ["bim", "dgop", "mop", "adopcion"],
    sourceId: "bim-dgop-2025",
    sourceType: "official_chile",
    scope: "Avance de implementación de BIM en la Dirección General de Obras Públicas (DGOP), total (Plan de Implementación BIM DGOP 2025-2028, tabla 'Avance de BIM por Dirección').",
    caveat: "Es avance de implementación institucional de BIM (Medición de Avance de BIM); no es porcentaje de proyectos ni de contratos con BIM.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "bim-dgop-nivel-central",
    title: "Avance de BIM en la DGOP — nivel central",
    description: "Avance de implementación de BIM en la DGOP a nivel central (Total, columna Central).",
    value: 26.5,
    suffix: "%",
    geography: "Chile",
    period: "2025",
    cutoffDate: "2025-01-01",
    category: "bim",
    tags: ["bim", "dgop", "mop", "central"],
    sourceId: "bim-dgop-2025",
    sourceType: "official_chile",
    scope: "Avance de implementación de BIM en la DGOP, nivel central (Plan de Implementación BIM DGOP 2025-2028, tabla 'Avance de BIM por Dirección').",
    caveat: "Es avance de implementación institucional de BIM (Medición de Avance de BIM); no es porcentaje de proyectos ni de contratos con BIM.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "bim-dgop-regiones",
    title: "Avance de BIM en la DGOP — regiones",
    description: "Avance de implementación de BIM en la DGOP a nivel regional (Total, columna Regional).",
    value: 8.9,
    suffix: "%",
    geography: "Chile",
    period: "2025",
    cutoffDate: "2025-01-01",
    category: "bim",
    tags: ["bim", "dgop", "mop", "regiones"],
    sourceId: "bim-dgop-2025",
    sourceType: "official_chile",
    scope: "Avance de implementación de BIM en la DGOP, nivel regional (Plan de Implementación BIM DGOP 2025-2028, tabla 'Avance de BIM por Dirección').",
    caveat: "Es avance de implementación institucional de BIM (Medición de Avance de BIM); no es porcentaje de proyectos ni de contratos con BIM.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "bim-dgop-arquitectura",
    title: "Avance de BIM en la DGOP — Dirección de Arquitectura",
    description: "Avance de implementación de BIM en la Dirección de Arquitectura (Porcentaje por Dirección).",
    value: 32.0,
    suffix: "%",
    geography: "Chile",
    period: "2025",
    cutoffDate: "2025-01-01",
    category: "bim",
    tags: ["bim", "dgop", "mop", "arquitectura"],
    sourceId: "bim-dgop-2025",
    sourceType: "official_chile",
    scope: "Avance de implementación de BIM en la Dirección de Arquitectura de la DGOP (Plan de Implementación BIM DGOP 2025-2028, tabla 'Avance de BIM por Dirección').",
    caveat: "Es avance de implementación institucional de BIM (Medición de Avance de BIM); no es porcentaje de proyectos ni de contratos con BIM.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "bim-dgop-aeropuertos",
    title: "Avance de BIM en la DGOP — Dirección de Aeropuertos",
    description: "Avance de implementación de BIM en la Dirección de Aeropuertos (Porcentaje por Dirección).",
    value: 30.5,
    suffix: "%",
    geography: "Chile",
    period: "2025",
    cutoffDate: "2025-01-01",
    category: "bim",
    tags: ["bim", "dgop", "mop", "aeropuertos"],
    sourceId: "bim-dgop-2025",
    sourceType: "official_chile",
    scope: "Avance de implementación de BIM en la Dirección de Aeropuertos de la DGOP (Plan de Implementación BIM DGOP 2025-2028, tabla 'Avance de BIM por Dirección').",
    caveat: "Es avance de implementación institucional de BIM (Medición de Avance de BIM); no es porcentaje de proyectos ni de contratos con BIM.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "bim-dgop-vialidad",
    title: "Avance de BIM en la DGOP — Dirección de Vialidad",
    description: "Avance de implementación de BIM en la Dirección de Vialidad (Porcentaje por Dirección).",
    value: 13.6,
    suffix: "%",
    geography: "Chile",
    period: "2025",
    cutoffDate: "2025-01-01",
    category: "bim",
    tags: ["bim", "dgop", "mop", "vialidad"],
    sourceId: "bim-dgop-2025",
    sourceType: "official_chile",
    scope: "Avance de implementación de BIM en la Dirección de Vialidad de la DGOP (Plan de Implementación BIM DGOP 2025-2028, tabla 'Avance de BIM por Dirección').",
    caveat: "Es avance de implementación institucional de BIM (Medición de Avance de BIM); no es porcentaje de proyectos ni de contratos con BIM.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "bim-dgop-obras-portuarias",
    title: "Avance de BIM en la DGOP — Dirección de Obras Portuarias",
    description: "Avance de implementación de BIM en la Dirección de Obras Portuarias (Porcentaje por Dirección).",
    value: 12.2,
    suffix: "%",
    geography: "Chile",
    period: "2025",
    cutoffDate: "2025-01-01",
    category: "bim",
    tags: ["bim", "dgop", "mop", "obras-portuarias"],
    sourceId: "bim-dgop-2025",
    sourceType: "official_chile",
    scope: "Avance de implementación de BIM en la Dirección de Obras Portuarias de la DGOP (Plan de Implementación BIM DGOP 2025-2028, tabla 'Avance de BIM por Dirección').",
    caveat: "Es avance de implementación institucional de BIM (Medición de Avance de BIM); no es porcentaje de proyectos ni de contratos con BIM.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),
  mk({
    slug: "bim-dgop-obras-hidraulicas",
    title: "Avance de BIM en la DGOP — Dirección de Obras Hidráulicas",
    description: "Avance de implementación de BIM en la Dirección de Obras Hidráulicas (Porcentaje por Dirección).",
    value: 0.3,
    suffix: "%",
    geography: "Chile",
    period: "2025",
    cutoffDate: "2025-01-01",
    category: "bim",
    tags: ["bim", "dgop", "mop", "obras-hidraulicas"],
    sourceId: "bim-dgop-2025",
    sourceType: "official_chile",
    scope: "Avance de implementación de BIM en la Dirección de Obras Hidráulicas de la DGOP (Plan de Implementación BIM DGOP 2025-2028, tabla 'Avance de BIM por Dirección').",
    caveat: "Es avance de implementación institucional de BIM (Medición de Avance de BIM); no es porcentaje de proyectos ni de contratos con BIM.",
    lastVerifiedAt: "2026-08-27",
    nextReviewAt: "2027-08-27",
  }),

  // ---- P1-8 · MOP — 70 obras estratégicas (comunicado abril 2026) ----
  // Magnitud de la cartera de obra pública priorizada. NO es industrialización.
  mk({
    slug: "mop-obras-priorizadas",
    title: "Obras estratégicas priorizadas por el MOP",
    description: "Obras de infraestructura pública priorizadas por el MOP en abril de 2026.",
    value: 70,
    unit: "obras",
    geography: "Chile",
    period: "2026-2030",
    cutoffDate: "2026-04-21",
    category: "otro",
    tags: ["infraestructura", "mop", "obra-publica"],
    sourceId: "mop-obras-2026",
    sourceType: "official_chile",
    scope: "cartera priorizada tras un análisis técnico de más de 300 obras en distintos estados de ejecución",
    caveat: "Corresponde a la magnitud de la cartera de obra pública priorizada; no implica que esos proyectos se ejecuten con métodos industrializados.",
    lastVerifiedAt: "2026-08-28",
    nextReviewAt: "2027-02-28",
  }),
  mk({
    slug: "mop-inversion-pib",
    title: "Inversión de la cartera MOP como % del PIB",
    description: "Inversión asociada a la cartera priorizada del MOP, como porcentaje del PIB.",
    value: 8.6,
    suffix: "%",
    geography: "Chile",
    period: "2026-2030",
    cutoffDate: "2026-04-21",
    category: "otro",
    tags: ["infraestructura", "mop", "inversion", "pib"],
    sourceId: "mop-obras-2026",
    sourceType: "official_chile",
    scope: "inversión asociada a la cartera priorizada, como porcentaje del PIB",
    caveat: "Corresponde a la magnitud de la cartera de obra pública priorizada; no implica que esos proyectos se ejecuten con métodos industrializados.",
    lastVerifiedAt: "2026-08-28",
    nextReviewAt: "2027-02-28",
  }),
  mk({
    // Rango: se guarda como VALOR-STRING (mismo patrón que nch3744), con la
    // precisión exacta en el scope. No lleva contador.
    slug: "mop-empleos-proyectados",
    title: "Empleos proyectados por la cartera MOP",
    description: "Empleos directos e indirectos proyectados por la cartera priorizada del MOP, hacia 2030.",
    value: "200.000 a 250.000",
    unit: "empleos",
    geography: "Chile",
    period: "2026-2030",
    cutoffDate: "2026-04-21",
    category: "otro",
    tags: ["infraestructura", "mop", "empleo"],
    sourceId: "mop-obras-2026",
    sourceType: "official_chile",
    scope: "empleos directos e indirectos proyectados al término del ciclo de ejecución, hacia 2030",
    caveat: "Corresponde a la magnitud de la cartera de obra pública priorizada; no implica que esos proyectos se ejecuten con métodos industrializados.",
    lastVerifiedAt: "2026-08-28",
    nextReviewAt: "2027-02-28",
  }),
];

export const INDICADORES: Record<string, DataIndicator> = Object.fromEntries(
  LISTA.map((i) => [i.slug, i])
);

// Lista original (conserva orden de declaración) para validaciones/recorridos.
export const INDICADORES_LISTA = LISTA;
